# 📈 Bitcoin ETL Project (Local Version)

In this project we will extract cryptocurrency market data from the CoinGecko API using the `pycoingecko` library and transforms it into a pandas DataFrame for further analysis as a pre cursor to when we use Amazon AWS!

In [7]:
https://docs.coingecko.com/reference/setting-up-your-api-key

SyntaxError: invalid syntax (1616845149.py, line 1)

In [8]:
# ✅ Install dependencies
!pip install pycoingecko pandas

Requirement already satisfied: pycoingecko in /Users/av/jupyter-env/lib/python3.13/site-packages (3.2.0)
Requirement already satisfied: pandas in /Users/av/jupyter-env/lib/python3.13/site-packages (2.3.0)
Requirement already satisfied: requests in /Users/av/jupyter-env/lib/python3.13/site-packages (from pycoingecko) (2.32.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/av/jupyter-env/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/av/jupyter-env/lib/python3.13/site-packages (from requests->pycoingecko) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/av/jupyter-env/lib/python3.13/site-packages (from requests->pycoingecko) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/av/jupyter-env/lib/python3.13/site-packages (from requests->pycoingecko) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/av/jupyter-env/lib/python3.13/site-packages (from requests->pycoingecko) (2025.4.26)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip

In [9]:
# 📦 Import packages
from pycoingecko import CoinGeckoAPI
from datetime import datetime

This calls the get_coins_markets method from the CoinGecko API.
It fetches market data (like price, market cap, volume) for the top 50 coins.
vs_currency='usd' means all prices will be shown in US dollars.
per_page=50 means you’re asking for 50 results on one page.

API = Application Programming Interface
It’s a way for software programs to talk to each other. Like a waiter..
2 ways to connect:
    
API KEY: Basially a password. You get it from the API provider (like OpenWeather, YouTube, etc.)
Open Authorization 2( OAUTH2): Used to get access tokens(temporay badge access)
The API gives you a Client ID (public) and Client Secret (private)
You use these to request permission to access data on behalf of a user

API Key = Simple, direct access
Client ID + Secret = Used to get tokens (for login-style access)
Bearer Token = The actual token you use after being authorized

CoinGecko’s public API, no client_id, client_secret, or API key is required. It’s a free, public, unauthenticated API, which is why this line works out of the box

When you connect to most APIs, the service needs to know who you are and if you're allowed to access the data. You prove this using:

In [11]:
# 🔄 Extract Data from CoinGecko
cg = CoinGeckoAPI() #This creates a CoinGeckoAPI object from the pycoingecko library.

# Get top 50 cryptocurrencies by market cap in USD
raw_data = cg.get_coins_markets(vs_currency='usd', per_page=50)

raw_data

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 106059,
  'market_cap': 2108637548979,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 2108637548979,
  'total_volume': 25488537485,
  'high_24h': 107216,
  'low_24h': 105402,
  'price_change_24h': -1113.7164334055706,
  'price_change_percentage_24h': -1.03918,
  'market_cap_change_24h': -22216837249.01831,
  'market_cap_change_percentage_24h': -1.04263,
  'circulating_supply': 19886246.0,
  'total_supply': 19886246.0,
  'max_supply': 21000000.0,
  'ath': 111814,
  'ath_change_percentage': -5.18374,
  'ath_date': '2025-05-22T18:41:28.492Z',
  'atl': 67.81,
  'atl_change_percentage': 156247.99235,
  'atl_date': '2013-07-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:50.749Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 2426.53,
  'market_cap': 292687719568,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 292687719568,
  'total_volume': 12073794389,
  'high_24h': 2487.35,
  'low_24h': 2393.31,
  'price_change_24h': -59.713026933354286,
  'price_change_percentage_24h': -2.40174,
  'market_cap_change_24h': -7332706518.829102,
  'market_cap_change_percentage_24h': -2.44407,
  'circulating_supply': 120717388.8264203,
  'total_supply': 120717388.8264203,
  'max_supply': None,
  'ath': 4878.26,
  'ath_change_percentage': -50.30645,
  'ath_date': '2021-11-10T14:24:19.604Z',
  'atl': 0.432979,
  'atl_change_percentage': 559784.35759,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 29.573814635553532,
   'currency': 'btc',
   'percentage': 2957.3814635553535},
  'last_updated': '2025-07-02T03:24:52.300Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 1.0,
  'market_cap': 157829420214,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 157829420214,
  'total_volume': 28245684096,
  'high_24h': 1.0,
  'low_24h': 1.0,
  'price_change_24h': -0.000193306399427273,
  'price_change_percentage_24h': -0.01933,
  'market_cap_change_24h': 80799583,
  'market_cap_change_percentage_24h': 0.05122,
  'circulating_supply': 157826202745.2649,
  'total_supply': 157826202745.2649,
  'max_supply': None,
  'ath': 1.32,
  'ath_change_percentage': -24.41811,
  'ath_date': '2018-07-24T00:00:00.000Z',
  'atl': 0.572521,
  'atl_change_percentage': 74.66964,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:46.745Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 2.18,
  'market_cap': 128494306967,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 217735982182,
  'total_volume': 2639667075,
  'high_24h': 2.24,
  'low_24h': 2.15,
  'price_change_24h': -0.05141590966235876,
  'price_change_percentage_24h': -2.30525,
  'market_cap_change_24h': -3015134024.7458496,
  'market_cap_change_percentage_24h': -2.29271,
  'circulating_supply': 59005546715.0,
  'total_supply': 99985991375.0,
  'max_supply': 100000000000.0,
  'ath': 3.4,
  'ath_change_percentage': -35.91514,
  'ath_date': '2018-01-07T00:00:00.000Z',
  'atl': 0.00268621,
  'atl_change_percentage': 80976.85928,
  'atl_date': '2014-05-22T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:44.821Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 649.16,
  'market_cap': 94643214503,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 94643214503,
  'total_volume': 592094752,
  'high_24h': 656.61,
  'low_24h': 644.68,
  'price_change_24h': -7.4445667371629725,
  'price_change_percentage_24h': -1.13379,
  'market_cap_change_24h': -1168856730.2767181,
  'market_cap_change_percentage_24h': -1.21995,
  'circulating_supply': 145887575.79,
  'total_supply': 145887575.79,
  'max_supply': 200000000.0,
  'ath': 788.84,
  'ath_change_percentage': -17.75896,
  'ath_date': '2024-12-04T10:35:25.220Z',
  'atl': 0.0398177,
  'atl_change_percentage': 1629208.76177,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:49.184Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 148.7,
  'market_cap': 79461390466,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 89820847286,
  'total_volume': 4110155593,
  'high_24h': 153.82,
  'low_24h': 145.46,
  'price_change_24h': -4.856983903318564,
  'price_change_percentage_24h': -3.16293,
  'market_cap_change_24h': -2527952929.5032043,
  'market_cap_change_percentage_24h': -3.08327,
  'circulating_supply': 534609014.0848654,
  'total_supply': 604306498.1601076,
  'max_supply': None,
  'ath': 293.31,
  'ath_change_percentage': -49.32824,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 0.500801,
  'atl_change_percentage': 29577.71071,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:45.656Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/usdc.png?1696506694',
  'current_price': 0.999828,
  'market_cap': 61599544586,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 61601840458,
  'total_volume': 6548431942,
  'high_24h': 0.999937,
  'low_24h': 0.999802,
  'price_change_24h': 1.956e-05,
  'price_change_percentage_24h': 0.00196,
  'market_cap_change_24h': 123115409,
  'market_cap_change_percentage_24h': 0.20026,
  'circulating_supply': 61610148751.94681,
  'total_supply': 61612445019.55438,
  'max_supply': None,
  'ath': 1.17,
  'ath_change_percentage': -14.73894,
  'ath_date': '2019-05-08T00:40:28.300Z',
  'atl': 0.877647,
  'atl_change_percentage': 13.92532,
  'atl_date': '2023-03-11T08:02:13.981Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:48.897Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193',
  'current_price': 0.281052,
  'market_cap': 26641814528,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 26641816645,
  'total_volume': 405650410,
  'high_24h': 0.281087,
  'low_24h': 0.278083,
  'price_change_24h': 0.00131309,
  'price_change_percentage_24h': 0.4694,
  'market_cap_change_24h': 125616468,
  'market_cap_change_percentage_24h': 0.47373,
  'circulating_supply': 94793651354.031,
  'total_supply': 94793658885.8738,
  'max_supply': None,
  'ath': 0.431288,
  'ath_change_percentage': -34.85935,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.00180434,
  'atl_change_percentage': 15470.44509,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 146.92201605097983,
   'currency': 'usd',
   'percentage': 14692.201605097984},
  'last_updated': '2025-07-02T03:24:45.960Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 0.159081,
  'market_cap': 23825949693,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 23831368549,
  'total_volume': 734592164,
  'high_24h': 0.164902,
  'low_24h': 0.157198,
  'price_change_24h': -0.005626084783849961,
  'price_change_percentage_24h': -3.41581,
  'market_cap_change_24h': -833334338.8891258,
  'market_cap_change_percentage_24h': -3.37939,
  'circulating_supply': 149888936383.7052,
  'total_supply': 149923026383.7052,
  'max_supply': None,
  'ath': 0.731578,
  'ath_change_percentage': -78.28558,
  'ath_date': '2021-05-08T05:08:23.458Z',
  'atl': 8.69e-05,
  'atl_change_percentage': 182697.52013,
  'atl_date': '2015-05-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:50.516Z'},
 {'id': 'staked-ether',
  'symbol': 'steth',
  'name': 'Lido Staked Ether',
  'image': 'https://coin-images.coingecko.com/coins/images/13442/large/steth_logo.png?1696513206',
  'current_price': 2426.7,
  'market_cap': 22067535287,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 22067535287,
  'total_volume': 10748256,
  'high_24h': 2486.53,
  'low_24h': 2392.04,
  'price_change_24h': -58.31783936937427,
  'price_change_percentage_24h': -2.34678,
  'market_cap_change_24h': -523464307.6950264,
  'market_cap_change_percentage_24h': -2.31714,
  'circulating_supply': 9102047.608232444,
  'total_supply': 9102047.608232444,
  'max_supply': None,
  'ath': 4829.57,
  'ath_change_percentage': -49.80679,
  'ath_date': '2021-11-10T14:40:47.256Z',
  'atl': 482.9,
  'atl_change_percentage': 401.99534,
  'atl_date': '2020-12-22T04:08:21.854Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:45.018Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 0.547056,
  'market_cap': 19747482015,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 24598535085,
  'total_volume': 642881228,
  'high_24h': 0.569122,
  'low_24h': 0.537969,
  'price_change_24h': -0.021379724238933195,
  'price_change_percentage_24h': -3.76115,
  'market_cap_change_24h': -758021423.5612564,
  'market_cap_change_percentage_24h': -3.69667,
  'circulating_supply': 36125593968.2479,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 3.09,
  'ath_change_percentage': -82.29033,
  'ath_date': '2021-09-02T06:00:10.474Z',
  'atl': 0.01925275,
  'atl_change_percentage': 2739.50011,
  'atl_date': '2020-03-13T02:22:55.044Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:49.557Z'},
 {'id': 'wrapped-bitcoin',
  'symbol': 'wbtc',
  'name': 'Wrapped Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png?1696507857',
  'current_price': 106028,
  'market_cap': 13658200578,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 13658200578,
  'total_volume': 157087572,
  'high_24h': 107206,
  'low_24h': 105239,
  'price_change_24h': -1149.2553962657985,
  'price_change_percentage_24h': -1.0723,
  'market_cap_change_24h': -126199896.27229881,
  'market_cap_change_percentage_24h': -0.91553,
  'circulating_supply': 128850.89873878,
  'total_supply': 128850.89873878,
  'max_supply': 128850.89873878,
  'ath': 111685,
  'ath_change_percentage': -5.06795,
  'ath_date': '2025-05-22T18:56:49.172Z',
  'atl': 3139.17,
  'atl_change_percentage': 3277.48769,
  'atl_date': '2019-04-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:47.535Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 37.47,
  'market_cap': 12500013880,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 37432880830,
  'total_volume': 231326055,
  'high_24h': 39.51,
  'low_24h': 36.88,
  'price_change_24h': -1.8206547656560588,
  'price_change_percentage_24h': -4.63401,
  'market_cap_change_24h': -618447560.3959312,
  'market_cap_change_percentage_24h': -4.71433,
  'circulating_supply': 333928180.0,
  'total_supply': 999990391.0,
  'max_supply': 1000000000.0,
  'ath': 45.57,
  'ath_change_percentage': -18.47258,
  'ath_date': '2025-06-16T14:36:35.939Z',
  'atl': 3.81,
  'atl_change_percentage': 875.3723,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:51.519Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 501.18,
  'market_cap': 9971418387,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 9971418387,
  'total_volume': 369342140,
  'high_24h': 526.64,
  'low_24h': 499.76,
  'price_change_24h': -22.557311519771986,
  'price_change_percentage_24h': -4.30697,
  'market_cap_change_24h': -445860018.5048065,
  'market_cap_change_percentage_24h': -4.28,
  'circulating_supply': 19891531.14665078,
  'total_supply': 19891531.14665078,
  'max_supply': 21000000.0,
  'ath': 3785.82,
  'ath_change_percentage': -86.75445,
  'ath_date': '2017-12-20T00:00:00.000Z',
  'atl': 76.93,
  'atl_change_percentage': 551.78907,
  'atl_date': '2018-12-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:49.067Z'},
 {'id': 'wrapped-steth',
  'symbol': 'wsteth',
  'name': 'Wrapped stETH',
  'image': 'https://coin-images.coingecko.com/coins/images/18834/large/wstETH.png?1696518295',
  'current_price': 2925.02,
  'market_cap': 9945806445,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 9945806445,
  'total_volume': 12188715,
  'high_24h': 2999.63,
  'low_24h': 2878.25,
  'price_change_24h': -73.3428439345189,
  'price_change_percentage_24h': -2.4461,
  'market_cap_change_24h': -225721331.3700924,
  'market_cap_change_percentage_24h': -2.21915,
  'circulating_supply': 3401408.66394975,
  'total_supply': 3401408.66394975,
  'max_supply': None,
  'ath': 7256.02,
  'ath_change_percentage': -59.70413,
  'ath_date': '2022-05-13T15:09:54.509Z',
  'atl': 558.54,
  'atl_change_percentage': 423.48555,
  'atl_date': '2022-05-13T01:36:45.053Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:46.970Z'},
 {'id': 'sui',
  'symbol': 'sui',
  'name': 'Sui',
  'image': 'https://coin-images.coingecko.com/coins/images/26375/large/sui-ocean-square.png?1727791290',
  'current_price': 2.7,
  'market_cap': 9324468956,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 26988213578,
  'total_volume': 566042447,
  'high_24h': 2.81,
  'low_24h': 2.67,
  'price_change_24h': -0.08672831973321227,
  'price_change_percentage_24h': -3.11066,
  'market_cap_change_24h': -143145798.84727478,
  'market_cap_change_percentage_24h': -1.51195,
  'circulating_supply': 3455015252.817221,
  'total_supply': 10000000000.0,
  'max_supply': 10000000000.0,
  'ath': 5.35,
  'ath_change_percentage': -49.4805,
  'ath_date': '2025-01-04T22:56:18.063Z',
  'atl': 0.364846,
  'atl_change_percentage': 640.32796,
  'atl_date': '2023-10-19T10:40:30.078Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:46.230Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/chainlink-new-logo.png?1696502009',
  'current_price': 12.92,
  'market_cap': 8758269213,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 12915896763,
  'total_volume': 262352560,
  'high_24h': 13.31,
  'low_24h': 12.81,
  'price_change_24h': -0.3598015477620251,
  'price_change_percentage_24h': -2.70848,
  'market_cap_change_24h': -247677053.69314766,
  'market_cap_change_percentage_24h': -2.75015,
  'circulating_supply': 678099970.4527868,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 52.7,
  'ath_change_percentage': -75.48731,
  'ath_date': '2021-05-10T00:13:57.214Z',
  'atl': 0.148183,
  'atl_change_percentage': 8617.15228,
  'atl_date': '2017-11-29T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:51.063Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 8.94,
  'market_cap': 8251765240,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 8806858073,
  'total_volume': 1812787,
  'high_24h': 9.09,
  'low_24h': 8.9,
  'price_change_24h': -0.13930086337627579,
  'price_change_percentage_24h': -1.53442,
  'market_cap_change_24h': -126186079.958642,
  'market_cap_change_percentage_24h': -1.50617,
  'circulating_supply': 923140241.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 10.14,
  'ath_change_percentage': -11.79002,
  'ath_date': '2025-03-10T09:26:43.294Z',
  'atl': 0.799859,
  'atl_change_percentage': 1017.71901,
  'atl_date': '2019-12-24T15:14:35.376Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:52.230Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 0.999816,
  'market_cap': 7318832870,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 7318832870,
  'total_volume': 3146107,
  'high_24h': 0.999961,
  'low_24h': 0.999654,
  'price_change_24h': -5.095337247929e-05,
  'price_change_percentage_24h': -0.0051,
  'market_cap_change_24h': 102453274,
  'market_cap_change_percentage_24h': 1.41973,
  'circulating_supply': 7320544024.52395,
  'total_supply': 7320544024.52395,
  'max_supply': None,
  'ath': 1.057,
  'ath_change_percentage': -5.43984,
  'ath_date': '2024-10-29T05:40:51.197Z',
  'atl': 0.948265,
  'atl_change_percentage': 5.43523,
  'atl_date': '2024-10-03T13:19:28.826Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:46.127Z'},
 {'id': 'avalanche-2',
  'symbol': 'avax',
  'name': 'Avalanche',
  'image': 'https://coin-images.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png?1696512369',
  'current_price': 17.26,
  'market_cap': 7282359874,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 7886183683,
  'total_volume': 238237811,
  'high_24h': 17.84,
  'low_24h': 17.0,
  'price_change_24h': -0.541011926579106,
  'price_change_percentage_24h': -3.03883,
  'market_cap_change_24h': -221074579.77231026,
  'market_cap_change_percentage_24h': -2.94631,
  'circulating_supply': 422146307.8901629,
  'total_supply': 457148971.3111975,
  'max_supply': 720000000.0,
  'ath': 144.96,
  'ath_change_percentage': -88.09446,
  'ath_date': '2021-11-21T14:18:56.538Z',
  'atl': 2.8,
  'atl_change_percentage': 516.13794,
  'atl_date': '2020-12-31T13:15:21.540Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:49.030Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 0.227769,
  'market_cap': 7115623645,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 11386674931,
  'total_volume': 213585682,
  'high_24h': 0.23858,
  'low_24h': 0.223395,
  'price_change_24h': -0.010585865651234122,
  'price_change_percentage_24h': -4.44123,
  'market_cap_change_24h': -325728298.6275692,
  'market_cap_change_percentage_24h': -4.37727,
  'circulating_supply': 31246513952.96751,
  'total_supply': 50001786892.81784,
  'max_supply': 50001786892.81784,
  'ath': 0.875563,
  'ath_change_percentage': -73.97471,
  'ath_date': '2018-01-03T00:00:00.000Z',
  'atl': 0.00047612,
  'atl_change_percentage': 47758.98552,
  'atl_date': '2015-03-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:45.785Z'},
 {'id': 'the-open-network',
  'symbol': 'ton',
  'name': 'Toncoin',
  'image': 'https://coin-images.coingecko.com/coins/images/17980/large/photo_2024-09-10_17.09.00.jpeg?1725963446',
  'current_price': 2.8,
  'market_cap': 6900734376,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 14354607412,
  'total_volume': 168921743,
  'high_24h': 2.89,
  'low_24h': 2.75,
  'price_change_24h': -0.09575763934450476,
  'price_change_percentage_24h': -3.31025,
  'market_cap_change_24h': -236675042.41634083,
  'market_cap_change_percentage_24h': -3.31598,
  'circulating_supply': 2468129827.983382,
  'total_supply': 5134096285.073858,
  'max_supply': None,
  'ath': 8.25,
  'ath_change_percentage': -66.1227,
  'ath_date': '2024-06-15T00:36:51.509Z',
  'atl': 0.519364,
  'atl_change_percentage': 438.37001,
  'atl_date': '2021-09-21T00:33:11.092Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:46.115Z'},
 {'id': 'shiba-inu',
  'symbol': 'shib',
  'name': 'Shiba Inu',

📦 Step 1: Understand the Raw JSON (raw_data)

When we call the CoinGecko API , it returns a LIST of dictionaries.
Each dictionary represents one coin and contains a lot of details like name, symbol, price, etc.

In [12]:
import sys
print(sys.version)

3.13.3 (main, Apr  8 2025, 13:54:08) [Clang 16.0.0 (clang-1600.0.26.6)]

In [13]:
# Preview raw JSON
raw_data[:2]  # Display first 2 entries, aka all the columns but 2 rows

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 106059,
  'market_cap': 2108637548979,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 2108637548979,
  'total_volume': 25488537485,
  'high_24h': 107216,
  'low_24h': 105402,
  'price_change_24h': -1113.7164334055706,
  'price_change_percentage_24h': -1.03918,
  'market_cap_change_24h': -22216837249.01831,
  'market_cap_change_percentage_24h': -1.04263,
  'circulating_supply': 19886246.0,
  'total_supply': 19886246.0,
  'max_supply': 21000000.0,
  'ath': 111814,
  'ath_change_percentage': -5.18374,
  'ath_date': '2025-05-22T18:41:28.492Z',
  'atl': 67.81,
  'atl_change_percentage': 156247.99235,
  'atl_date': '2013-07-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-07-02T03:24:50.749Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 2426.53,
  'market_cap': 292687719568,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 292687719568,
  'total_volume': 12073794389,
  'high_24h': 2487.35,
  'low_24h': 2393.31,
  'price_change_24h': -59.713026933354286,
  'price_change_percentage_24h': -2.40174,
  'market_cap_change_24h': -7332706518.829102,
  'market_cap_change_percentage_24h': -2.44407,
  'circulating_supply': 120717388.8264203,
  'total_supply': 120717388.8264203,
  'max_supply': None,
  'ath': 4878.26,
  'ath_change_percentage': -50.30645,
  'ath_date': '2021-11-10T14:24:19.604Z',
  'atl': 0.432979,
  'atl_change_percentage': 559784.35759,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 29.573814635553532,
   'currency': 'btc',
   'percentage': 2957.3814635553535},
  'last_updated': '2025-07-02T03:24:52.300Z'}]

In [ ]:
#let us first try to grab some data
raw_data[0]['id']

In [26]:
#remember
dic = {'apples':2, "pears":3, "grapes":8}
dic['apples']

2

In [31]:
raw_data[0]['symbol']

'btc'

In [30]:
raw_data[1]['roi']['percentage']

2933.487679457216

In [ ]:
we have the raw data and lets say we are a finance company who needs to have organized groupings of data or DATASETS this is how you would
do it. 
Logically we have metadata and market data

🧱 Step 2: Build a Clean List of Metadata

We only want certain descriptive fields about each coin (not the changing prices or volumes). So we loop through the list and extract the metadata fields we care about:

In [14]:
metadata_list = []

for coin in raw_data:
    coin_id = coin['id']
    coin_symbol = coin['symbol']
    coin_name = coin['name']
    coin_image = coin['image']
    coin_rank = coin['market_cap_rank']
    coin_max_supply = coin['max_supply']
#We group the selected fields into a dictionary so we can treat each coin’s data like a row:
    coin_metadata = {
        'coin_id': coin_id,
        'symbol': coin_symbol,
        'name': coin_name,
        'image_url': coin_image,
        'market_cap_rank': coin_rank,
        'max_supply': coin_max_supply
    }
#Now each coin_metadata is like a row in a table.
#We append this to our list of rows:
    metadata_list.append(coin_metadata)

In [15]:
metadata_list

[{'coin_id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'market_cap_rank': 1,
  'max_supply': 21000000.0},
 {'coin_id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image_url': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'market_cap_rank': 2,
  'max_supply': None},
 {'coin_id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image_url': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'market_cap_rank': 3,
  'max_supply': None},
 {'coin_id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image_url': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'market_cap_rank': 4,
  'max_supply': 100000000000.0},
 {'coin_id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image_url': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'market_cap_rank': 5,
  'max_supply': 200000000.0},
 {'coin_id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image_url': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'market_cap_rank': 6,
  'max_supply': None},
 {'coin_id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image_url': 'https://coin-images.coingecko.com/coins/images/6319/large/usdc.png?1696506694',
  'market_cap_rank': 7,
  'max_supply': None},
 {'coin_id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image_url': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193',
  'market_cap_rank': 8,
  'max_supply': None},
 {'coin_id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'market_cap_rank': 9,
  'max_supply': None},
 {'coin_id': 'staked-ether',
  'symbol': 'steth',
  'name': 'Lido Staked Ether',
  'image_url': 'https://coin-images.coingecko.com/coins/images/13442/large/steth_logo.png?1696513206',
  'market_cap_rank': 10,
  'max_supply': None},
 {'coin_id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image_url': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'market_cap_rank': 11,
  'max_supply': 45000000000.0},
 {'coin_id': 'wrapped-bitcoin',
  'symbol': 'wbtc',
  'name': 'Wrapped Bitcoin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png?1696507857',
  'market_cap_rank': 12,
  'max_supply': 128850.89873878},
 {'coin_id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image_url': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'market_cap_rank': 13,
  'max_supply': 1000000000.0},
 {'coin_id': 'wrapped-steth',
  'symbol': 'wsteth',
  'name': 'Wrapped stETH',
  'image_url': 'https://coin-images.coingecko.com/coins/images/18834/large/wstETH.png?1696518295',
  'market_cap_rank': 14,
  'max_supply': None},
 {'coin_id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image_url': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'market_cap_rank': 15,
  'max_supply': 21000000.0},
 {'coin_id': 'sui',
  'symbol': 'sui',
  'name': 'Sui',
  'image_url': 'https://coin-images.coingecko.com/coins/images/26375/large/sui-ocean-square.png?1727791290',
  'market_cap_rank': 16,
  'max_supply': 10000000000.0},
 {'coin_id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image_url': 'https://coin-images.coingecko.com/coins/images/877/large/chainlink-new-logo.png?1696502009',
  'market_cap_rank': 17,
  'max_supply': 1000000000.0},
 {'coin_id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image_url': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'market_cap_rank': 18,
  'max_supply': None},
 {'coin_id': 'avalanche-2',
  'symbol': 'avax',
  'name': 'Avalanche',
  'image_url': 'https://coin-images.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png?1696512369',
  'market_cap_rank': 19,
  'max_supply': 720000000.0},
 {'coin_id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image_url': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'market_cap_rank': 20,
  'max_supply': 50001786892.81785},
 {'coin_id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image_url': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'market_cap_rank': 21,
  'max_supply': None},
 {'coin_id': 'the-open-network',
  'symbol': 'ton',
  'name': 'Toncoin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/17980/large/photo_2024-09-10_17.09.00.jpeg?1725963446',
  'market_cap_rank': 22,
  'max_supply': None},
 {'coin_id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'market_cap_rank': 23,
  'max_supply': 400000000.0},
 {'coin_id': 'shiba-inu',
  'symbol': 'shib',
  'name': 'Shiba Inu',
  'image_url': 'https://coin-images.coingecko.com/coins/images/11939/large/shiba.png?1696511800',
  'market_cap_rank': 24,
  'max_supply': None},
 {'coin_id': 'weth',
  'symbol': 'weth',
  'name': 'WETH',
  'image_url': 'https://coin-images.coingecko.com/coins/images/2518/large/weth.png?1696503332',
  'market_cap_rank': 25,
  'max_supply': None},
 {'coin_id': 'litecoin',
  'symbol': 'ltc',
  'name': 'Litecoin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/2/large/litecoin.png?1696501400',
  'market_cap_rank': 26,
  'max_supply': 84000000.0},
 {'coin_id': 'wrapped-eeth',
  'symbol': 'weeth',
  'name': 'Wrapped eETH',
  'image_url': 'https://coin-images.coingecko.com/coins/images/33033/large/weETH.png?1701438396',
  'market_cap_rank': 27,
  'max_supply': None},
 {'coin_id': 'binance-bridged-usdt-bnb-smart-chain',
  'symbol': 'bsc-usd',
  'name': 'Binance Bridged USDT (BNB Smart Chain)',
  'image_url': 'https://coin-images.coingecko.com/coins/images/35021/large/USDT.png?1707233575',
  'market_cap_rank': 28,
  'max_supply': None},
 {'coin_id': 'hedera-hashgraph',
  'symbol': 'hbar',
  'name': 'Hedera',
  'image_url': 'https://coin-images.coingecko.com/coins/images/3688/large/hbar.png?1696504364',
  'market_cap_rank': 29,
  'max_supply': 50000000000.0},
 {'coin_id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image_url': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'market_cap_rank': 30,
  'max_supply': None},
 {'coin_id': 'bitget-token',
  'symbol': 'bgb',
  'name': 'Bitget Token',
  'image_url': 'https://coin-images.coingecko.com/coins/images/11610/large/Bitget_logo.png?1736925727',
  'market_cap_rank': 31,
  'max_supply': 2000000000.0},
 {'coin_id': 'ethena-usde',
  'symbol': 'usde',
  'name': 'Ethena USDe',
  'image_url': 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059',
  'market_cap_rank': 32,
  'max_supply': None},
 {'coin_id': 'polkadot',
  'symbol': 'dot',
  'name': 'Polkadot',
  'image_url': 'https://coin-images.coingecko.com/coins/images/12171/large/polkadot.png?1696512008',
  'market_cap_rank': 33,
  'max_supply': None},
 {'coin_id': 'coinbase-wrapped-btc',
  'symbol': 'cbbtc',
  'name': 'Coinbase Wrapped BTC',
  'image_url': 'https://coin-images.coingecko.com/coins/images/40143/large/cbbtc.webp?1726136727',
  'market_cap_rank': 34,
  'max_supply': None},
 {'coin_id': 'uniswap',
  'symbol': 'uni',
  'name': 'Uniswap',
  'image_url': 'https://coin-images.coingecko.com/coins/images/12504/large/uniswap-logo.png?1720676669',
  'market_cap_rank': 35,
  'max_supply': 1000000000.0},
 {'coin_id': 'pi-network',
  'symbol': 'pi',
  'name': 'Pi Network',
  'image_url': 'https://coin-images.coingecko.com/coins/images/54342/large/pi_network.jpg?1739347576',
  'market_cap_rank': 36,
  'max_supply': 100000000000.0},
 {'coin_id': 'pepe',
  'symbol': 'pepe',
  'name': 'Pepe',
  'image_url': 'https://coin-images.coingecko.com/coins/images/29850/large/pepe-token.jpeg?1696528776',
  'market_cap_rank': 37,
  'max_supply': 420690000000000.0},
 {'coin_id': 'aave',
  'symbol': 'aave',
  'name': 'Aave',
  'image_url': 'https://coin-images.coingecko.com/coins/images/12645/large/aave-token-round.png?1720472354',
  'market_cap_rank': 38,
  'max_supply': 16000000.0},
 {'coin_id': 'dai',
  'symbol': 'dai',
  'name': 'Dai',
  'image_url': 'https://coin-images.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996',
  'market_cap_rank': 39,
  'max_supply': None},
 {'coin_id': 'ethena-staked-usde',
  'symbol': 'susde',
  'name': 'Ethena Staked USDe',
  'image_url': 'https://coin-images.coingecko.com/coins/images/33669/large/sUSDe-Symbol-Color.png?1716307680',
  'market_cap_rank': 40,
  'max_supply': None},
 {'coin_id': 'aptos',
  'symbol': 'apt',
  'name': 'Aptos',
  'image_url': 'https://coin-images.coingecko.com/coins/images/26455/large/aptos_round.png?1696525528',
  'market_cap_rank': 41,
  'max_supply': None},
 {'coin_id': 'okb',
  'symbol': 'okb',
  'name': 'OKB',
  'image_url': 'https://coin-images.coingecko.com/coins/images/4463/large/WeChat_Image_20220118095654.png?1696505053',
  'market_cap_rank': 42,
  'max_supply': 300000000.0},
 {'coin_id': 'bittensor',
  'symbol': 'tao',
  'name': 'Bittensor',
  'image_url': 'https://coin-images.coingecko.com/coins/images/28452/large/ARUsPeNQ_400x400.jpeg?1696527447',
  'market_cap_rank': 43,
  'max_supply': 21000000.0},
 {'coin_id': 'blackrock-usd-institutional-digital-liquidity-fund',
  'symbol': 'buidl',
  'name': 'BlackRock USD Institutional Digital Liquidity Fund',
  'image_url': 'https://coin-images.coingecko.com/coins/images/36291/large/blackrock.png?1711013223',
  'market_cap_rank': 44,
  'max_supply': None},
 {'coin_id': 'jito-staked-sol',
  'symbol': 'jitosol',
  'name': 'Jito Staked SOL',
  'image_url': 'https://coin-images.coingecko.com/coins/images/28046/large/JitoSOL-200.png?1696527060',
  'market_cap_rank': 45,
  'max_supply': None},
 {'coin_id': 'near',
  'symbol': 'near',
  'name': 'NEAR Protocol',
  'image_url': 'https://coin-images.coingecko.com/coins/images/10365/large/near.jpg?1696510367',
  'market_cap_rank': 46,
  'max_supply': None},
 {'coin_id': 'internet-computer',
  'symbol': 'icp',
  'name': 'Internet Computer',
  'image_url': 'https://coin-images.coingecko.com/coins/images/14495/large/Internet_Computer_logo.png?1696514180',
  'market_cap_rank': 47,
  'max_supply': None},
 {'coin_id': 'crypto-com-chain',
  'symbol': 'cro',
  'name': 'Cronos',
  'image_url': 'https://coin-images.coingecko.com/coins/images/7310/large/cro_token_logo.png?1696507599',
  'market_cap_rank': 48,
  'max_supply': 100000000000.0},
 {'coin_id': 'ethereum-classic',
  'symbol': 'etc',
  'name': 'Ethereum Classic',
  'image_url': 'https://coin-images.coingecko.com/coins/images/453/large/ethereum-classic-logo.png?1696501717',
  'market_cap_rank': 49,
  'max_supply': 210700000.0},
 {'coin_id': 'susds',
  'symbol': 'susds',
  'name': 'sUSDS',
  'image_url': 'https://coin-images.coingecko.com/coins/images/52721/large/sUSDS_Coin.png?1734086971',
  'market_cap_rank': 50,
  'max_supply': None}]

🧱 Step 3: Build a Clean List of Market DAta

We only want certain descriptive fields about each coin (not the changing prices or volumes). So we loop through the list and extract the metadata fields we care about:

In [33]:
market_data_list = []

for coin in raw_data:
    coin_id = coin['id']
    current_price = coin['current_price']
    market_cap = coin['market_cap']
    total_volume = coin['total_volume']
    high_24h = coin['high_24h']
    low_24h = coin['low_24h']
    price_change_24h = coin['price_change_24h']
    price_change_pct_24h = coin['price_change_percentage_24h']
    market_cap_change_24h = coin['market_cap_change_24h']
    market_cap_change_pct_24h = coin['market_cap_change_percentage_24h']

    coin_market_data = {
        'coin_id': coin_id,
        'current_price': current_price,
        'market_cap': market_cap,
        'total_volume': total_volume,
        'high_24h': high_24h,
        'low_24h': low_24h,
        'price_change_24h': price_change_24h,
        'price_change_pct_24h': price_change_pct_24h,
        'market_cap_change_24h': market_cap_change_24h,
        'market_cap_change_pct_24h': market_cap_change_pct_24h
    }

    market_data_list.append(coin_market_data)

In [43]:
#market_data_list

📊 Step 4: Convert to DataFrame

Now that we have a list of dictionaries (like a table), we use pandas to convert it into a real DataFrame:

In [35]:
import pandas as pd
df_metadata = pd.DataFrame(metadata_list)

In [38]:
# Display DataFrame
df_metadata.head()

,coin_id,symbol,name,image_url,market_cap_rank,max_supply
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,1,2.100000e+07
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2,NaN
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,3,NaN
3,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,4,1.000000e+11
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,5,2.000000e+08

In [39]:
#get a summary of data
df_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   coin_id          50 non-null     object
 1   symbol           50 non-null     object
 2   name             50 non-null     object
 3   image_url        50 non-null     object
 4   market_cap_rank  50 non-null     int64
 5   max_supply       23 non-null     float64
dtypes: float64(1), int64(1), object(4)
memory usage: 2.5+ KB

In [40]:
df_metadata = df_metadata.drop_duplicates(subset=['coin_id'])

In [42]:
df_marketdata = pd.DataFrame(market_data_list)

In [45]:
df_marketdata.head()

,coin_id,current_price,market_cap,total_volume,high_24h,low_24h,price_change_24h,price_change_pct_24h,market_cap_change_24h,market_cap_change_pct_24h
0,bitcoin,107249.00,2132660458082,9.563125e+09,107530.00,106905.00,145.800000,0.13613,3.213395e+09,0.15090
1,ethereum,2433.09,293658499059,5.103819e+09,2445.34,2410.91,9.310000,0.38403,1.126715e+09,0.38516
2,tether,1.00,157523409654,1.308218e+10,1.00,1.00,-0.000096,-0.00960,-6.772592e+06,-0.00430
3,ripple,2.18,128866085651,2.088537e+09,2.21,2.11,0.076984,3.65312,4.624205e+09,3.72194
4,binancecoin,647.89,94519624560,3.087252e+08,648.02,644.56,1.450000,0.22357,2.199967e+08,0.23330

In [ ]:
df_marketdata.info()

In [46]:
df_marketdata = df_marketdata.drop_duplicates(subset=['coin_id'])