# 📈 Bitcoin ETL Project (Local Version)

In this project we will extract cryptocurrency market data from the CoinGecko API using the `pycoingecko` library and transforms it into a pandas DataFrame for further analysis as a pre cursor to when we use Amazon AWS!

`You work for a finance company, they want to analyze the crypto market every single morning during business meetings. The raw online data is messy and contains unwanted information for key business insights. We want the data to be brought in, cleaned and organized into market data and meta data and finally stored in a cloud location to be queried and linked to business dashboards`

https://docs.coingecko.com/reference/setting-up-your-api-key

In [4]:
#install dependencies
!pip install pycoingecko pandas

Requirement already satisfied: pycoingecko in /Users/av/jupyter-env/lib/python3.13/site-packages (3.2.0)
Requirement already satisfied: pandas in /Users/av/jupyter-env/lib/python3.13/site-packages (2.3.0)
Requirement already satisfied: requests in /Users/av/jupyter-env/lib/python3.13/site-packages (from pycoingecko) (2.32.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/av/jupyter-env/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/av/jupyter-env/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/av/jupyter-env/lib/python3.13/site-packages (from requests->pycoingecko) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/av/jupyter-env/lib/python3.13/site-packages (from requests->pycoingecko) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/av/jupyter-env/lib/python3.13/site-packages (from requests->pycoingecko) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/av/jupyter-env/lib/python3.13/site-packages (from requests->pycoingecko) (2025.4.26)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [6]:
#import packages
from pycoingecko import CoinGeckoAPI

When you connect to most APIs, the service needs to know who you are and if you're allowed to access the data. You prove this using:

API = Application Programming Interface It’s a way for software programs to talk to each other. Like a waiter.. 2 ways to connect:

1. API KEY: Basically a password. You get it from the API provider (like OpenWeather, YouTube, etc.)Simple, direct access

2. Open Authorization 2( OAUTH2): Used to get access tokens(temporay badge access) 
The API gives you a Client ID (public) and Client Secret (private) --> Temporary Token (bearer)
You use these tokens to request permission to access data on behalf of a user

CoinGecko’s public API, no client_id, client_secret, or API key is required. It’s a free, public, unauthenticated API, which is why this line works out of the box

In [7]:
#Extract data from CoinGecko
cg = CoinGeckoAPI() # COINGECKO OBJECT FROM PYTHON LIBRARY
raw_data = cg.get_coins_markets(vs_currency = 'usd', per_page = 50)

In [8]:
raw_data

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 117829,
  'market_cap': 2346720953499,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 2346720953499,
  'total_volume': 73586281209,
  'high_24h': 124128,
  'low_24h': 117640,
  'price_change_24h': -3944.717342972741,
  'price_change_percentage_24h': -3.23939,
  'market_cap_change_24h': -77848074594.06055,
  'market_cap_change_percentage_24h': -3.2108,
  'circulating_supply': 19906312.0,
  'total_supply': 19906312.0,
  'max_supply': 21000000.0,
  'ath': 124128,
  'ath_change_percentage': -5.02204,
  'ath_date': '2025-08-14T00:37:02.582Z',
  'atl': 67.81,
  'atl_change_percentage': 173762.29959,
  'atl_date': '2013-07-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.871Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 4532.39,
  'market_cap': 548351156148,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 548351156148,
  'total_volume': 64614666756,
  'high_24h': 4779.0,
  'low_24h': 4527.03,
  'price_change_24h': -205.32474408149756,
  'price_change_percentage_24h': -4.33384,
  'market_cap_change_24h': -23201230591.35437,
  'market_cap_change_percentage_24h': -4.05934,
  'circulating_supply': 120708311.7641891,
  'total_supply': 120708311.7641891,
  'max_supply': None,
  'ath': 4878.26,
  'ath_change_percentage': -6.87535,
  'ath_date': '2021-11-10T14:24:19.604Z',
  'atl': 0.432979,
  'atl_change_percentage': 1049111.266,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 50.4405226738721,
   'currency': 'btc',
   'percentage': 5044.05226738721},
  'last_updated': '2025-08-14T18:13:13.237Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 3.07,
  'market_cap': 182238082615,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 307228646806,
  'total_volume': 11026388437,
  'high_24h': 3.34,
  'low_24h': 3.06,
  'price_change_24h': -0.20649853846365573,
  'price_change_percentage_24h': -6.30389,
  'market_cap_change_24h': -12067860268.423218,
  'market_cap_change_percentage_24h': -6.21075,
  'circulating_supply': 59308385925.0,
  'total_supply': 99985880506.0,
  'max_supply': 100000000000.0,
  'ath': 3.65,
  'ath_change_percentage': -15.66899,
  'ath_date': '2025-07-18T03:40:53.808Z',
  'atl': 0.00268621,
  'atl_change_percentage': 114374.71562,
  'atl_date': '2014-05-22T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.994Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 1.0,
  'market_cap': 165086538617,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 165086538617,
  'total_volume': 164780693245,
  'high_24h': 1.001,
  'low_24h': 1.0,
  'price_change_24h': 0.00033615,
  'price_change_percentage_24h': 0.03361,
  'market_cap_change_24h': 58865910,
  'market_cap_change_percentage_24h': 0.03567,
  'circulating_supply': 165024459754.7903,
  'total_supply': 165024459754.7903,
  'max_supply': None,
  'ath': 1.32,
  'ath_change_percentage': -24.38931,
  'ath_date': '2018-07-24T00:00:00.000Z',
  'atl': 0.572521,
  'atl_change_percentage': 74.7362,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:13.343Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 833.78,
  'market_cap': 116074726816,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 116074726816,
  'total_volume': 2690525449,
  'high_24h': 866.96,
  'low_24h': 829.68,
  'price_change_24h': -10.136669898619061,
  'price_change_percentage_24h': -1.20114,
  'market_cap_change_24h': -1464498939.2854767,
  'market_cap_change_percentage_24h': -1.24597,
  'circulating_supply': 139287782.18,
  'total_supply': 139287782.18,
  'max_supply': 200000000.0,
  'ath': 866.96,
  'ath_change_percentage': -3.88386,
  'ath_date': '2025-08-14T10:43:32.298Z',
  'atl': 0.0398177,
  'atl_change_percentage': 2092661.51425,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.764Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 193.09,
  'market_cap': 104355912979,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 117441830127,
  'total_volume': 14575684799,
  'high_24h': 209.18,
  'low_24h': 191.72,
  'price_change_24h': -7.052199813995145,
  'price_change_percentage_24h': -3.52359,
  'market_cap_change_24h': -3144536657.1637115,
  'market_cap_change_percentage_24h': -2.92514,
  'circulating_supply': 539786725.7542609,
  'total_supply': 607474355.2286055,
  'max_supply': None,
  'ath': 293.31,
  'ath_change_percentage': -34.104,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 0.500801,
  'atl_change_percentage': 38494.3293,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.786Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/usdc.png?1696506694',
  'current_price': 0.999802,
  'market_cap': 67077872258,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 67325968595,
  'total_volume': 25927141396,
  'high_24h': 0.999855,
  'low_24h': 0.999711,
  'price_change_24h': -6.535987209899e-06,
  'price_change_percentage_24h': -0.00065,
  'market_cap_change_24h': 667425531,
  'market_cap_change_percentage_24h': 1.005,
  'circulating_supply': 67091002191.36086,
  'total_supply': 67339147090.6048,
  'max_supply': None,
  'ath': 1.17,
  'ath_change_percentage': -14.74506,
  'ath_date': '2019-05-08T00:40:28.300Z',
  'atl': 0.877647,
  'atl_change_percentage': 13.91714,
  'atl_date': '2023-03-11T08:02:13.981Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:13.217Z'},
 {'id': 'staked-ether',
  'symbol': 'steth',
  'name': 'Lido Staked Ether',
  'image': 'https://coin-images.coingecko.com/coins/images/13442/large/steth_logo.png?1696513206',
  'current_price': 4525.49,
  'market_cap': 40011158534,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 40011158534,
  'total_volume': 153147961,
  'high_24h': 4769.92,
  'low_24h': 4493.23,
  'price_change_24h': -204.23581633463345,
  'price_change_percentage_24h': -4.31814,
  'market_cap_change_24h': -1755158429.4321442,
  'market_cap_change_percentage_24h': -4.20233,
  'circulating_supply': 8840763.499929141,
  'total_supply': 8842346.789635146,
  'max_supply': None,
  'ath': 4829.57,
  'ath_change_percentage': -6.06503,
  'ath_date': '2021-11-10T14:40:47.256Z',
  'atl': 482.9,
  'atl_change_percentage': 839.46802,
  'atl_date': '2020-12-22T04:08:21.854Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:19.036Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193',
  'current_price': 0.358334,
  'market_cap': 33925744010,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 33925942680,
  'total_volume': 2293355417,
  'high_24h': 0.369488,
  'low_24h': 0.358099,
  'price_change_24h': -0.002807744495100073,
  'price_change_percentage_24h': -0.77746,
  'market_cap_change_24h': -307236719.03902054,
  'market_cap_change_percentage_24h': -0.89749,
  'circulating_supply': 94685815104.68283,
  'total_supply': 94685801458.06366,
  'max_supply': None,
  'ath': 0.431288,
  'ath_change_percentage': -16.92296,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.00180434,
  'atl_change_percentage': 19757.747,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 187.59675471787432,
   'currency': 'usd',
   'percentage': 18759.675471787432},
  'last_updated': '2025-08-14T18:13:12.782Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 0.222995,
  'market_cap': 33611452009,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 33612378762,
  'total_volume': 4865177488,
  'high_24h': 0.253948,
  'low_24h': 0.222593,
  'price_change_24h': -0.020618063605453985,
  'price_change_percentage_24h': -8.46344,
  'market_cap_change_24h': -2970233461.824669,
  'market_cap_change_percentage_24h': -8.11945,
  'circulating_supply': 150512046383.7052,
  'total_supply': 150517496383.7052,
  'max_supply': None,
  'ath': 0.731578,
  'ath_change_percentage': -69.46183,
  'ath_date': '2021-05-08T05:08:23.458Z',
  'atl': 8.69e-05,
  'atl_change_percentage': 256978.14407,
  'atl_date': '2015-05-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.601Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 0.902098,
  'market_cap': 32869827847,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 40677197544,
  'total_volume': 5805966334,
  'high_24h': 1.014,
  'low_24h': 0.871277,
  'price_change_24h': 0.0278367,
  'price_change_percentage_24h': 3.18403,
  'market_cap_change_24h': 1115693110,
  'market_cap_change_percentage_24h': 3.51354,
  'circulating_supply': 36362934086.75214,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 3.09,
  'ath_change_percentage': -70.69445,
  'ath_date': '2021-09-02T06:00:10.474Z',
  'atl': 0.01925275,
  'atl_change_percentage': 4598.73852,
  'atl_date': '2020-03-13T02:22:55.044Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.829Z'},
 {'id': 'wrapped-steth',
  'symbol': 'wsteth',
  'name': 'Wrapped stETH',
  'image': 'https://coin-images.coingecko.com/coins/images/18834/large/wstETH.png?1696518295',
  'current_price': 5495.48,
  'market_cap': 17576054093,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 17576054093,
  'total_volume': 127646191,
  'high_24h': 5776.07,
  'low_24h': 5464.45,
  'price_change_24h': -221.1370837783261,
  'price_change_percentage_24h': -3.86832,
  'market_cap_change_24h': -789671922.6812096,
  'market_cap_change_percentage_24h': -4.2997,
  'circulating_supply': 3198469.785012209,
  'total_supply': 3198051.22709717,
  'max_supply': None,
  'ath': 7256.02,
  'ath_change_percentage': -24.25364,
  'ath_date': '2022-05-13T15:09:54.509Z',
  'atl': 558.54,
  'atl_change_percentage': 884.02455,
  'atl_date': '2022-05-13T01:36:45.053Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:17.761Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/chainlink-new-logo.png?1696502009',
  'current_price': 22.31,
  'market_cap': 15133428388,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 22317400159,
  'total_volume': 2012096752,
  'high_24h': 24.25,
  'low_24h': 22.3,
  'price_change_24h': -1.4311680320332023,
  'price_change_percentage_24h': -6.02879,
  'market_cap_change_24h': -946902195.6564598,
  'market_cap_change_percentage_24h': -5.88857,
  'circulating_supply': 678099970.4527868,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 52.7,
  'ath_change_percentage': -57.6713,
  'ath_date': '2021-05-10T00:13:57.214Z',
  'atl': 0.148183,
  'atl_change_percentage': 14952.84269,
  'atl_date': '2017-11-29T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.822Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 45.25,
  'market_cap': 15003246342,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 44943042094,
  'total_volume': 539428642,
  'high_24h': 48.82,
  'low_24h': 44.4,
  'price_change_24h': -1.992064159134479,
  'price_change_percentage_24h': -4.21658,
  'market_cap_change_24h': -755354567.3409252,
  'market_cap_change_percentage_24h': -4.79328,
  'circulating_supply': 333772999.4341414,
  'total_supply': 999835210.4341414,
  'max_supply': 1000000000.0,
  'ath': 49.75,
  'ath_change_percentage': -8.99274,
  'ath_date': '2025-07-14T05:06:23.602Z',
  'atl': 3.81,
  'atl_change_percentage': 1088.81156,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:16.002Z'},
 {'id': 'wrapped-bitcoin',
  'symbol': 'wbtc',
  'name': 'Wrapped Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png?1696507857',
  'current_price': 117847,
  'market_cap': 14968581237,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 14968581237,
  'total_volume': 509332498,
  'high_24h': 123882,
  'low_24h': 117569,
  'price_change_24h': -3811.8478816083225,
  'price_change_percentage_24h': -3.13323,
  'market_cap_change_24h': -495274796.4574909,
  'market_cap_change_percentage_24h': -3.20279,
  'circulating_supply': 127037.57872278,
  'total_supply': 127037.57872278,
  'max_supply': 127037.57872278,
  'ath': 123882,
  'ath_change_percentage': -4.86694,
  'ath_date': '2025-08-14T00:40:53.782Z',
  'atl': 3139.17,
  'atl_change_percentage': 3654.24703,
  'atl_date': '2019-04-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.626Z'},
 {'id': 'wrapped-beacon-eth',
  'symbol': 'wbeth',
  'name': 'Wrapped Beacon ETH',
  'image': 'https://coin-images.coingecko.com/coins/images/30061/large/wbeth-icon.png?1696528983',
  'current_price': 4872.0,
  'market_cap': 14441232690,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 14441232690,
  'total_volume': 43802278,
  'high_24h': 5142.46,
  'low_24h': 4858.0,
  'price_change_24h': -216.78271453531124,
  'price_change_percentage_24h': -4.26001,
  'market_cap_change_24h': -574942224.9773483,
  'market_cap_change_percentage_24h': -3.82882,
  'circulating_supply': 2964154.258285347,
  'total_supply': 2964154.258285347,
  'max_supply': None,
  'ath': 5142.46,
  'ath_change_percentage': -5.25909,
  'ath_date': '2025-08-14T04:32:33.945Z',
  'atl': 1501.6,
  'atl_change_percentage': 224.45467,
  'atl_date': '2025-04-09T03:57:40.245Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.383Z'},
 {'id': 'sui',
  'symbol': 'sui',
  'name': 'Sui',
  'image': 'https://coin-images.coingecko.com/coins/images/26375/large/sui-ocean-square.png?1727791290',
  'current_price': 3.76,
  'market_cap': 13247081512,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 37720291507,
  'total_volume': 2668270207,
  'high_24h': 4.16,
  'low_24h': 3.75,
  'price_change_24h': -0.23747573987916848,
  'price_change_percentage_24h': -5.93654,
  'market_cap_change_24h': -775012651.6795845,
  'market_cap_change_percentage_24h': -5.52708,
  'circulating_supply': 3511924479.569998,
  'total_supply': 10000000000.0,
  'max_supply': 10000000000.0,
  'ath': 5.35,
  'ath_change_percentage': -29.50213,
  'ath_date': '2025-01-04T22:56:18.063Z',
  'atl': 0.364846,
  'atl_change_percentage': 933.09693,
  'atl_date': '2023-10-19T10:40:30.078Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:13.214Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 0.422022,
  'market_cap': 13224869430,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 21120397782,
  'total_volume': 871259898,
  'high_24h': 0.465095,
  'low_24h': 0.418613,
  'price_change_24h': -0.029952130953082357,
  'price_change_percentage_24h': -6.62696,
  'market_cap_change_24h': -919604527.7912331,
  'market_cap_change_percentage_24h': -6.50151,
  'circulating_supply': 31309405708.80982,
  'total_supply': 50001786891.0645,
  'max_supply': 50001786891.0645,
  'ath': 0.875563,
  'ath_change_percentage': -51.69499,
  'ath_date': '2018-01-03T00:00:00.000Z',
  'atl': 0.00047612,
  'atl_change_percentage': 88730.08811,
  'atl_date': '2015-03-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.668Z'},
 {'id': 'wrapped-eeth',
  'symbol': 'weeth',
  'name': 'Wrapped eETH',
  'image': 'https://coin-images.coingecko.com/coins/images/33033/large/weETH.png?1701438396',
  'current_price': 4866.17,
  'market_cap': 12647043574,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 12647043574,
  'total_volume': 48900247,
  'high_24h': 5124.17,
  'low_24h': 4850.89,
  'price_change_24h': -209.39260929233205,
  'price_change_percentage_24h': -4.1255,
  'market_cap_change_24h': -563236536.6641922,
  'market_cap_change_percentage_24h': -4.26362,
  'circulating_supply': 2597098.380166228,
  'total_supply': 2597098.380166228,
  'max_supply': None,
  'ath': 5124.17,
  'ath_change_percentage': -4.95623,
  'ath_date': '2025-08-14T04:21:20.683Z',
  'atl': 1505.24,
  'atl_change_percentage': 223.55107,
  'atl_date': '2025-04-09T03:45:31.391Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.492Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 589.22,
  'market_cap': 11731414298,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 11731440075,
  'total_volume': 443378144,
  'high_24h': 626.02,
  'low_24h': 586.68,
  'price_change_24h': -23.717185062277508,
  'price_change_percentage_24h': -3.86945,
  'market_cap_change_24h': -483761600.3815403,
  'market_cap_change_percentage_24h': -3.96033,
  'circulating_supply': 19911249.89665078,
  'total_supply': 19911293.64665078,
  'max_supply': 21000000.0,
  'ath': 3785.82,
  'ath_change_percentage': -84.4358,
  'ath_date': '2017-12-20T00:00:00.000Z',
  'atl': 76.93,
  'atl_change_percentage': 665.88582,
  'atl_date': '2018-12-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.660Z'},
 {'id': 'ethena-usde',
  'symbol': 'usde',
  'name': 'Ethena USDe',
  'image': 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059',
  'current_price': 1.001,
  'market_cap': 10968720718,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 10968720718,
  'total_volume': 740059437,
  'high_24h': 1.002,
  'low_24h': 0.998585,
  'price_change_24h': -0.000336486318164297,
  'price_change_percentage_24h': -0.03361,
  'market_cap_change_24h': 93851997,
  'market_cap_change_percentage_24h': 0.86302,
  'circulating_supply': 10961297761.25967,
  'total_supply': 10961297761.25967,
  'max_supply': None,
  'ath': 1.032,
  'ath_change_percentage': -3.04413,
  'ath_date': '2023-12-20T15:38:34.596Z',
  'atl': 0.929486,
  'atl_change_percentage': 7.6578,
  'atl_date': '2024-10-04T07:57:15.809Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.495Z'},
 {'id': 'hedera-hashgraph',
  'symbol': 'hbar',
  'name': 'Hedera',
  'image': 'https://coin-images.coingecko.com/coins/images/3688/large/hbar.png?1696504364',
  'current_price': 0.248491,
  'market_cap': 10536967167,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 12427815556,
  'total_volume': 626406778,
  'high_24h': 0.275162,
  'low_24h': 0.247702,
  'price_change_24h': -0.015318782589314295,
  'price_change_percentage_24h': -5.80675,
  'market_cap_change_24h': -646542182.2239246,
  'market_cap_change_percentage_24h': -5.78121,
  'circulating_supply': 42392676005.97186,
  'total_supply': 50000000000.0,
  'max_supply': 50000000000.0,
  'ath': 0.569229,
  'ath_change_percentage': -56.24848,
  'ath_date': '2021-09-15T10:40:28.318Z',
  'atl': 0.00986111,
  'atl_change_percentage': 2425.54047,
  'atl_date': '2020-01-02T17:30:24.852Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.513Z'},
 {'id': 'weth',
  'symbol': 'weth',
  'name': 'WETH',

In [ ]:
#list of dictionaries
# [ {},{},{},50    ]

In [12]:
raw_data[0:2]

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 117829,
  'market_cap': 2346720953499,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 2346720953499,
  'total_volume': 73586281209,
  'high_24h': 124128,
  'low_24h': 117640,
  'price_change_24h': -3944.717342972741,
  'price_change_percentage_24h': -3.23939,
  'market_cap_change_24h': -77848074594.06055,
  'market_cap_change_percentage_24h': -3.2108,
  'circulating_supply': 19906312.0,
  'total_supply': 19906312.0,
  'max_supply': 21000000.0,
  'ath': 124128,
  'ath_change_percentage': -5.02204,
  'ath_date': '2025-08-14T00:37:02.582Z',
  'atl': 67.81,
  'atl_change_percentage': 173762.29959,
  'atl_date': '2013-07-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2025-08-14T18:13:12.871Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 4532.39,
  'market_cap': 548351156148,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 548351156148,
  'total_volume': 64614666756,
  'high_24h': 4779.0,
  'low_24h': 4527.03,
  'price_change_24h': -205.32474408149756,
  'price_change_percentage_24h': -4.33384,
  'market_cap_change_24h': -23201230591.35437,
  'market_cap_change_percentage_24h': -4.05934,
  'circulating_supply': 120708311.7641891,
  'total_supply': 120708311.7641891,
  'max_supply': None,
  'ath': 4878.26,
  'ath_change_percentage': -6.87535,
  'ath_date': '2021-11-10T14:24:19.604Z',
  'atl': 0.432979,
  'atl_change_percentage': 1049111.266,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 50.4405226738721,
   'currency': 'btc',
   'percentage': 5044.05226738721},
  'last_updated': '2025-08-14T18:13:13.237Z'}]

In [13]:
raw_data[0]['id']

'bitcoin'

In [14]:
raw_data[0]['symbol']

'btc'

In [15]:
#grabbed a dictionary, then grabbed a key and value
raw_data[1]['roi']['percentage']

5044.05226738721

In [ ]:
#market data: data market related : id, current_price,market cap total vol, high 24, low 24, pricechange24h, marketcapchange24,marketcapchange%
#meta data: data about the coin data : symbol, image, name, market_cap_rank, max_supply

In [ ]:
#build a list of market data dictionary objects(coins)

Build a Clean List of Market DAta

We only want certain descriptive fields about each coin (not the changing prices or volumes). So we loop through the list and extract the metadata fields we care about:

In [16]:
market_data_list = []

for coin in raw_data: #coin is a dictionary
    coin_id = coin['id'] #we use keys to grab values from dictss
    current_price = coin['current_price']
    market_cap = coin['market_cap']
    total_volume = coin['total_volume']
    high_24h = coin['high_24h']
    low_24h = coin['low_24h']
    price_change_24h = coin['price_change_24h']
    price_change_pct_24h = coin['price_change_percentage_24h']
    market_cap_change_24h = coin['market_cap_change_24h']
    market_cap_change_pct_24h = coin['market_cap_change_percentage_24h']

    coin_market_data = {
        'coin_id': coin_id,
        'current_price': current_price,
        'market_cap': market_cap,
        'total_volume': total_volume,
        'high_24h': high_24h,
        'low_24h': low_24h,
        'price_change_24h': price_change_24h,
        'price_change_pct_24h': price_change_pct_24h,
        'market_cap_change_24h': market_cap_change_24h,
        'market_cap_change_pct_24h': market_cap_change_pct_24h
    }

    market_data_list.append(coin_market_data)

In [17]:
market_data_list

[{'coin_id': 'bitcoin',
  'current_price': 117829,
  'market_cap': 2346720953499,
  'total_volume': 73586281209,
  'high_24h': 124128,
  'low_24h': 117640,
  'price_change_24h': -3944.717342972741,
  'price_change_pct_24h': -3.23939,
  'market_cap_change_24h': -77848074594.06055,
  'market_cap_change_pct_24h': -3.2108},
 {'coin_id': 'ethereum',
  'current_price': 4532.39,
  'market_cap': 548351156148,
  'total_volume': 64614666756,
  'high_24h': 4779.0,
  'low_24h': 4527.03,
  'price_change_24h': -205.32474408149756,
  'price_change_pct_24h': -4.33384,
  'market_cap_change_24h': -23201230591.35437,
  'market_cap_change_pct_24h': -4.05934},
 {'coin_id': 'ripple',
  'current_price': 3.07,
  'market_cap': 182238082615,
  'total_volume': 11026388437,
  'high_24h': 3.34,
  'low_24h': 3.06,
  'price_change_24h': -0.20649853846365573,
  'price_change_pct_24h': -6.30389,
  'market_cap_change_24h': -12067860268.423218,
  'market_cap_change_pct_24h': -6.21075},
 {'coin_id': 'tether',
  'current_price': 1.0,
  'market_cap': 165086538617,
  'total_volume': 164780693245,
  'high_24h': 1.001,
  'low_24h': 1.0,
  'price_change_24h': 0.00033615,
  'price_change_pct_24h': 0.03361,
  'market_cap_change_24h': 58865910,
  'market_cap_change_pct_24h': 0.03567},
 {'coin_id': 'binancecoin',
  'current_price': 833.78,
  'market_cap': 116074726816,
  'total_volume': 2690525449,
  'high_24h': 866.96,
  'low_24h': 829.68,
  'price_change_24h': -10.136669898619061,
  'price_change_pct_24h': -1.20114,
  'market_cap_change_24h': -1464498939.2854767,
  'market_cap_change_pct_24h': -1.24597},
 {'coin_id': 'solana',
  'current_price': 193.09,
  'market_cap': 104355912979,
  'total_volume': 14575684799,
  'high_24h': 209.18,
  'low_24h': 191.72,
  'price_change_24h': -7.052199813995145,
  'price_change_pct_24h': -3.52359,
  'market_cap_change_24h': -3144536657.1637115,
  'market_cap_change_pct_24h': -2.92514},
 {'coin_id': 'usd-coin',
  'current_price': 0.999802,
  'market_cap': 67077872258,
  'total_volume': 25927141396,
  'high_24h': 0.999855,
  'low_24h': 0.999711,
  'price_change_24h': -6.535987209899e-06,
  'price_change_pct_24h': -0.00065,
  'market_cap_change_24h': 667425531,
  'market_cap_change_pct_24h': 1.005},
 {'coin_id': 'staked-ether',
  'current_price': 4525.49,
  'market_cap': 40011158534,
  'total_volume': 153147961,
  'high_24h': 4769.92,
  'low_24h': 4493.23,
  'price_change_24h': -204.23581633463345,
  'price_change_pct_24h': -4.31814,
  'market_cap_change_24h': -1755158429.4321442,
  'market_cap_change_pct_24h': -4.20233},
 {'coin_id': 'tron',
  'current_price': 0.358334,
  'market_cap': 33925744010,
  'total_volume': 2293355417,
  'high_24h': 0.369488,
  'low_24h': 0.358099,
  'price_change_24h': -0.002807744495100073,
  'price_change_pct_24h': -0.77746,
  'market_cap_change_24h': -307236719.03902054,
  'market_cap_change_pct_24h': -0.89749},
 {'coin_id': 'dogecoin',
  'current_price': 0.222995,
  'market_cap': 33611452009,
  'total_volume': 4865177488,
  'high_24h': 0.253948,
  'low_24h': 0.222593,
  'price_change_24h': -0.020618063605453985,
  'price_change_pct_24h': -8.46344,
  'market_cap_change_24h': -2970233461.824669,
  'market_cap_change_pct_24h': -8.11945},
 {'coin_id': 'cardano',
  'current_price': 0.902098,
  'market_cap': 32869827847,
  'total_volume': 5805966334,
  'high_24h': 1.014,
  'low_24h': 0.871277,
  'price_change_24h': 0.0278367,
  'price_change_pct_24h': 3.18403,
  'market_cap_change_24h': 1115693110,
  'market_cap_change_pct_24h': 3.51354},
 {'coin_id': 'wrapped-steth',
  'current_price': 5495.48,
  'market_cap': 17576054093,
  'total_volume': 127646191,
  'high_24h': 5776.07,
  'low_24h': 5464.45,
  'price_change_24h': -221.1370837783261,
  'price_change_pct_24h': -3.86832,
  'market_cap_change_24h': -789671922.6812096,
  'market_cap_change_pct_24h': -4.2997},
 {'coin_id': 'chainlink',
  'current_price': 22.31,
  'market_cap': 15133428388,
  'total_volume': 2012096752,
  'high_24h': 24.25,
  'low_24h': 22.3,
  'price_change_24h': -1.4311680320332023,
  'price_change_pct_24h': -6.02879,
  'market_cap_change_24h': -946902195.6564598,
  'market_cap_change_pct_24h': -5.88857},
 {'coin_id': 'hyperliquid',
  'current_price': 45.25,
  'market_cap': 15003246342,
  'total_volume': 539428642,
  'high_24h': 48.82,
  'low_24h': 44.4,
  'price_change_24h': -1.992064159134479,
  'price_change_pct_24h': -4.21658,
  'market_cap_change_24h': -755354567.3409252,
  'market_cap_change_pct_24h': -4.79328},
 {'coin_id': 'wrapped-bitcoin',
  'current_price': 117847,
  'market_cap': 14968581237,
  'total_volume': 509332498,
  'high_24h': 123882,
  'low_24h': 117569,
  'price_change_24h': -3811.8478816083225,
  'price_change_pct_24h': -3.13323,
  'market_cap_change_24h': -495274796.4574909,
  'market_cap_change_pct_24h': -3.20279},
 {'coin_id': 'wrapped-beacon-eth',
  'current_price': 4872.0,
  'market_cap': 14441232690,
  'total_volume': 43802278,
  'high_24h': 5142.46,
  'low_24h': 4858.0,
  'price_change_24h': -216.78271453531124,
  'price_change_pct_24h': -4.26001,
  'market_cap_change_24h': -574942224.9773483,
  'market_cap_change_pct_24h': -3.82882},
 {'coin_id': 'sui',
  'current_price': 3.76,
  'market_cap': 13247081512,
  'total_volume': 2668270207,
  'high_24h': 4.16,
  'low_24h': 3.75,
  'price_change_24h': -0.23747573987916848,
  'price_change_pct_24h': -5.93654,
  'market_cap_change_24h': -775012651.6795845,
  'market_cap_change_pct_24h': -5.52708},
 {'coin_id': 'stellar',
  'current_price': 0.422022,
  'market_cap': 13224869430,
  'total_volume': 871259898,
  'high_24h': 0.465095,
  'low_24h': 0.418613,
  'price_change_24h': -0.029952130953082357,
  'price_change_pct_24h': -6.62696,
  'market_cap_change_24h': -919604527.7912331,
  'market_cap_change_pct_24h': -6.50151},
 {'coin_id': 'wrapped-eeth',
  'current_price': 4866.17,
  'market_cap': 12647043574,
  'total_volume': 48900247,
  'high_24h': 5124.17,
  'low_24h': 4850.89,
  'price_change_24h': -209.39260929233205,
  'price_change_pct_24h': -4.1255,
  'market_cap_change_24h': -563236536.6641922,
  'market_cap_change_pct_24h': -4.26362},
 {'coin_id': 'bitcoin-cash',
  'current_price': 589.22,
  'market_cap': 11731414298,
  'total_volume': 443378144,
  'high_24h': 626.02,
  'low_24h': 586.68,
  'price_change_24h': -23.717185062277508,
  'price_change_pct_24h': -3.86945,
  'market_cap_change_24h': -483761600.3815403,
  'market_cap_change_pct_24h': -3.96033},
 {'coin_id': 'ethena-usde',
  'current_price': 1.001,
  'market_cap': 10968720718,
  'total_volume': 740059437,
  'high_24h': 1.002,
  'low_24h': 0.998585,
  'price_change_24h': -0.000336486318164297,
  'price_change_pct_24h': -0.03361,
  'market_cap_change_24h': 93851997,
  'market_cap_change_pct_24h': 0.86302},
 {'coin_id': 'hedera-hashgraph',
  'current_price': 0.248491,
  'market_cap': 10536967167,
  'total_volume': 626406778,
  'high_24h': 0.275162,
  'low_24h': 0.247702,
  'price_change_24h': -0.015318782589314295,
  'price_change_pct_24h': -5.80675,
  'market_cap_change_24h': -646542182.2239246,
  'market_cap_change_pct_24h': -5.78121},
 {'coin_id': 'weth',
  'current_price': 4543.0,
  'market_cap': 10259359160,
  'total_volume': 142815731,
  'high_24h': 4780.97,
  'low_24h': 4505.13,
  'price_change_24h': -193.3436070763546,
  'price_change_pct_24h': -4.08212,
  'market_cap_change_24h': -823691447.2365761,
  'market_cap_change_pct_24h': -7.43199},
 {'coin_id': 'avalanche-2',
  'current_price': 23.66,
  'market_cap': 9990533374,
  'total_volume': 1113272061,
  'high_24h': 25.94,
  'low_24h': 23.54,
  'price_change_24h': -1.537861743775725,
  'price_change_pct_24h': -6.104,
  'market_cap_change_24h': -636854217.9821892,
  'market_cap_change_pct_24h': -5.99258},
 {'coin_id': 'litecoin',
  'current_price': 120.9,
  'market_cap': 9214851026,
  'total_volume': 1241076589,
  'high_24h': 133.6,
  'low_24h': 120.75,
  'price_change_24h': -9.232922204603952,
  'price_change_pct_24h': -7.09522,
  'market_cap_change_24h': -674392374.1455154,
  'market_cap_change_pct_24h': -6.81945},
 {'coin_id': 'the-open-network',
  'current_price': 3.41,
  'market_cap': 8736562593,
  'total_volume': 453518019,
  'high_24h': 3.63,
  'low_24h': 3.38,
  'price_change_24h': -0.09370480397178804,
  'price_change_pct_24h': -2.67741,
  'market_cap_change_24h': -241937352.405344,
  'market_cap_change_pct_24h': -2.69463},
 {'coin_id': 'leo-token',
  'current_price': 9.28,
  'market_cap': 8562995341,
  'total_volume': 4581109,
  'high_24h': 9.29,
  'low_24h': 9.23,
  'price_change_24h': 0.03063924,
  'price_change_pct_24h': 0.33137,
  'market_cap_change_24h': 28293245,
  'market_cap_change_pct_24h': 0.33151},
 {'coin_id': 'usds',
  'current_price': 0.999557,
  'market_cap': 7618217482,
  'total_volume': 27132849,
  'high_24h': 1.0,
  'low_24h': 0.999224,
  'price_change_24h': -7.4852929449754e-05,
  'price_change_pct_24h': -0.00749,
  'market_cap_change_24h': -123320193.74281406,
  'market_cap_change_pct_24h': -1.59297},
 {'coin_id': 'shiba-inu',
  'current_price': 1.285e-05,
  'market_cap': 7571320526,
  'total_volume': 433689723,
  'high_24h': 1.415e-05,
  'low_24h': 1.278e-05,
  'price_change_24h': -1.025999394884e-06,
  'price_change_pct_24h': -7.39603,
  'market_cap_change_24h': -602327172.1567554,
  'market_cap_change_pct_24h': -7.36914},
 {'coin_id': 'binance-bridged-usdt-bnb-smart-chain',
  'current_price': 0.998436,
  'market_cap': 6783599138,
  'total_volume': 2238065774,
  'high_24h': 1.009,
  'low_24h': 0.988595,
  'price_change_24h': -0.002095252398859548,
  'price_change_pct_24h': -0.20941,
  'market_cap_change_24h': -3139728.9240694046,
  'market_cap_change_pct_24h': -0.04626},
 {'coin_id': 'coinbase-wrapped-btc',
  'current_price': 117923,
  'market_cap': 6573077649,
  'total_volume': 796719123,
  'high_24h': 123939,
  'low_24h': 117450,
  'price_change_24h': -3700.283455751778,
  'price_change_pct_24h': -3.04241,
  'market_cap_change_24h': -178684599.9411707,
  'market_cap_change_pct_24h': -2.64649},
 {'coin_id': 'uniswap',
  'current_price': 10.9,
  'market_cap': 6547795283,
  'total_volume': 971758174,
  'high_24h': 12.22,
  'low_24h': 10.85,
  'price_change_24h': -1.1385725000126783,
  'price_change_pct_24h': -9.45704,
  'market_cap_change_24h': -691291060.488967,
  'market_cap_change_pct_24h': -9.54942},
 {'coin_id': 'whitebit',
  'current_price': 45.28,
  'market_cap': 6520092970,
  'total_volume': 90182076,
  'high_24h': 47.21,
  'low_24h': 45.18,
  'price_change_24h': -1.3165542487175728,
  'price_change_pct_24h': -2.82571,
  'market_cap_change_24h': -189456621.07606125,
  'market_cap_change_pct_24h': -2.82369},
 {'coin_id': 'polkadot',
  'current_price': 3.99,
  'market_cap': 6070206309,
  'total_volume': 540270259,
  'high_24h': 4.36,
  'low_24h': 3.96,
  'price_change_24h': -0.2445115417909669,
  'price_change_pct_24h': -5.77925,
  'market_cap_change_24h': -372819898.25958157,
  'market_cap_change_pct_24h': -5.78641},
 {'coin_id': 'okb',
  'current_price': 93.81,
  'market_cap': 5684692960,
  'total_volume': 1157029004,
  'high_24h': 113.53,
  'low_24h': 92.74,
  'price_change_24h': -9.551100887433094,
  'price_change_pct_24h': -9.24063,
  'market_cap_change_24h': -532517512.6386156,
  'market_cap_change_pct_24h': -8.56522},
 {'coin_id': 'ethena-staked-usde',
  'current_price': 1.19,
  'market_cap': 5498399352,
  'total_volume': 109107555,
  'high_24h': 1.19,
  'low_24h': 1.19,
  'price_change_24h': -0.000561450070664327,
  'price_change_pct_24h': -0.0473,
  'market_cap_change_24h': 19335237,
  'market_cap_change_pct_24h': 0.35289},
 {'coin_id': 'bitget-token',
  'current_price': 4.55,
  'market_cap': 5185317652,
  'total_volume': 308836325,
  'high_24h': 4.89,
  'low_24h': 4.54,
  'price_change_24h': -0.24679723760950978,
  'price_change_pct_24h': -5.14654,
  'market_cap_change_24h': -274616126.681653,
  'market_cap_change_pct_24h': -5.02966},
 {'coin_id': 'crypto-com-chain',
  'current_price': 0.151527,
  'market_cap': 4909400412,
  'total_volume': 48779095,
  'high_24h': 0.168316,
  'low_24h': 0.150516,
  'price_change_24h': -0.014015387517825995,
  'price_change_pct_24h': -8.46634,
  'market_cap_change_24h': -441563635.87551785,
  'market_cap_change_pct_24h': -8.25204},
 {'coin_id': 'ethena',
  'current_price': 0.727168,
  'market_cap': 4820555660,
  'total_volume': 1529839957,
  'high_24h': 0.781403,
  'low_24h': 0.704473,
  'price_change_24h': -0.05423531870807985,
  'price_change_pct_24h': -6.94076,
  'market_cap_change_24h': -384941699.57395077,
  'market_cap_change_pct_24h': -7.39491},
 {'coin_id': 'aave',
  'current_price': 310.1,
  'market_cap': 4717875401,
  'total_volume': 808795132,
  'high_24h': 339.63,
  'low_24h': 309.25,
  'price_change_24h': -17.231374421984356,
  'price_change_pct_24h': -5.26423,
  'market_cap_change_24h': -266526057.66504288,
  'market_cap_change_pct_24h': -5.3472},
 {'coin_id': 'pepe',
  'current_price': 1.109e-05,
  'market_cap': 4672092407,
  'total_volume': 1473870423,
  'high_24h': 1.26e-05,
  'low_24h': 1.109e-05,
  'price_change_24h': -1.148618766187e-06,
  'price_change_pct_24h': -9.38591,
  'market_cap_change_24h': -472263235.9958916,
  'market_cap_change_pct_24h': -9.18022},
 {'coin_id': 'monero',
  'current_price': 247.45,
  'market_cap': 4568916934,
  'total_volume': 58921500,
  'high_24h': 258.92,
  'low_24h': 246.3,
  'price_change_24h': -8.920204438954357,
  'price_change_pct_24h': -3.47939,
  'market_cap_change_24h': -201089754.3310051,
  'market_cap_change_pct_24h': -4.21571},
 {'coin_id': 'dai',
  'current_price': 0.999813,
  'market_cap': 4025076777,
  'total_volume': 195793484,
  'high_24h': 1.0,
  'low_24h': 0.999334,
  'price_change_24h': -0.000124813311667693,
  'price_change_pct_24h': -0.01248,
  'market_cap_change_24h': 95631767,
  'market_cap_change_pct_24h': 2.43372},
 {'coin_id': 'mantle',
  'current_price': 1.1,
  'market_cap': 3697099635,
  'total_volume': 396378074,
  'high_24h': 1.2,
  'low_24h': 1.085,
  'price_change_24h': -0.022169254164905672,
  'price_change_pct_24h': -1.97274,
  'market_cap_change_24h': -95984423.44203377,
  'market_cap_change_pct_24h': -2.53051},
 {'coin_id': 'bittensor',
  'current_price': 367.18,
  'market_cap': 3529108981,
  'total_volume': 215071345,
  'high_24h': 400.91,
  'low_24h': 365.93,
  'price_change_24h': -24.737800993524388,
  'price_change_pct_24h': -6.31201,
  'market_cap_change_24h': -240397256.6183877,
  'market_cap_change_pct_24h': -6.37742},
 {'coin_id': 'near',
  'current_price': 2.78,
  'market_cap': 3470880133,
  'total_volume': 520685419,
  'high_24h': 3.05,
  'low_24h': 2.77,
  'price_change_24h': -0.15897913850383416,
  'price_change_pct_24h': -5.406,
  'market_cap_change_24h': -189989856.42666817,
  'market_cap_change_pct_24h': -5.18975},
 {'coin_id': 'ethereum-classic',
  'current_price': 22.24,
  'market_cap': 3412128761,
  'total_volume': 284302867,
  'high_24h': 24.41,
  'low_24h': 22.15,
  'price_change_24h': -1.9074899221467838,
  'price_change_pct_24h': -7.89947,
  'market_cap_change_24h': -279933789.1549535,
  'market_cap_change_pct_24h': -7.58204},
 {'coin_id': 'aptos',
  'current_price': 4.74,
  'market_cap': 3244430760,
  'total_volume': 601934349,
  'high_24h': 5.14,
  'low_24h': 4.71,
  'price_change_24h': -0.23328994181219276,
  'price_change_pct_24h': -4.69376,
  'market_cap_change_24h': -155776991.25441313,
  'market_cap_change_pct_24h': -4.5814},
 {'coin_id': 'ondo-finance',
  'current_price': 0.995541,
  'market_cap': 3149417178,
  'total_volume': 377495933,
  'high_24h': 1.11,
  'low_24h': 0.991047,
  'price_change_24h': -0.0721458173013928,
  'price_change_pct_24h': -6.75721,
  'market_cap_change_24h': -222124911.79047537,
  'market_cap_change_pct_24h': -6.58823},
 {'coin_id': 'internet-computer',
  'current_price': 5.54,
  'market_cap': 2981686038,
  'total_volume': 106939821,
  'high_24h': 6.08,
  'low_24h': 5.52,
  'price_change_24h': -0.3931431404175765,
  'price_change_pct_24h': -6.62076,
  'market_cap_change_24h': -205966163.381248,
  'market_cap_change_pct_24h': -6.46138}]

Step 2: Build a Clean List of Metadata

We only want certain descriptive fields about each coin (not the changing prices or volumes). So we loop through the list and extract the metadata fields we care about:

In [19]:
meta_data_list = []

for coin in raw_data:
    coin_id = coin['id']
    coin_symbol = coin['symbol']
    coin_name = coin['name']
    coin_image = coin['image']
    coin_rank = coin['market_cap_rank']
    coin_max_supply = coin['max_supply']

    coin_metadata = {
        'coin_id': coin_id,
        'symbol': coin_symbol,
        'name': coin_name,
        'image_url': coin_image,
        'market_cap_rank': coin_rank,
        'max_supply': coin_max_supply
    }

    meta_data_list.append(coin_metadata)

In [20]:
meta_data_list

[{'coin_id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'market_cap_rank': 1,
  'max_supply': 21000000.0},
 {'coin_id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image_url': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'market_cap_rank': 2,
  'max_supply': None},
 {'coin_id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image_url': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'market_cap_rank': 3,
  'max_supply': 100000000000.0},
 {'coin_id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image_url': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'market_cap_rank': 4,
  'max_supply': None},
 {'coin_id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image_url': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'market_cap_rank': 5,
  'max_supply': 200000000.0},
 {'coin_id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image_url': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'market_cap_rank': 6,
  'max_supply': None},
 {'coin_id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image_url': 'https://coin-images.coingecko.com/coins/images/6319/large/usdc.png?1696506694',
  'market_cap_rank': 7,
  'max_supply': None},
 {'coin_id': 'staked-ether',
  'symbol': 'steth',
  'name': 'Lido Staked Ether',
  'image_url': 'https://coin-images.coingecko.com/coins/images/13442/large/steth_logo.png?1696513206',
  'market_cap_rank': 8,
  'max_supply': None},
 {'coin_id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image_url': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193',
  'market_cap_rank': 9,
  'max_supply': None},
 {'coin_id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'market_cap_rank': 10,
  'max_supply': None},
 {'coin_id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image_url': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'market_cap_rank': 11,
  'max_supply': 45000000000.0},
 {'coin_id': 'wrapped-steth',
  'symbol': 'wsteth',
  'name': 'Wrapped stETH',
  'image_url': 'https://coin-images.coingecko.com/coins/images/18834/large/wstETH.png?1696518295',
  'market_cap_rank': 12,
  'max_supply': None},
 {'coin_id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image_url': 'https://coin-images.coingecko.com/coins/images/877/large/chainlink-new-logo.png?1696502009',
  'market_cap_rank': 13,
  'max_supply': 1000000000.0},
 {'coin_id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image_url': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'market_cap_rank': 14,
  'max_supply': 1000000000.0},
 {'coin_id': 'wrapped-bitcoin',
  'symbol': 'wbtc',
  'name': 'Wrapped Bitcoin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png?1696507857',
  'market_cap_rank': 15,
  'max_supply': 127037.57872278},
 {'coin_id': 'wrapped-beacon-eth',
  'symbol': 'wbeth',
  'name': 'Wrapped Beacon ETH',
  'image_url': 'https://coin-images.coingecko.com/coins/images/30061/large/wbeth-icon.png?1696528983',
  'market_cap_rank': 16,
  'max_supply': None},
 {'coin_id': 'sui',
  'symbol': 'sui',
  'name': 'Sui',
  'image_url': 'https://coin-images.coingecko.com/coins/images/26375/large/sui-ocean-square.png?1727791290',
  'market_cap_rank': 17,
  'max_supply': 10000000000.0},
 {'coin_id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image_url': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'market_cap_rank': 18,
  'max_supply': 50001786891.0645},
 {'coin_id': 'wrapped-eeth',
  'symbol': 'weeth',
  'name': 'Wrapped eETH',
  'image_url': 'https://coin-images.coingecko.com/coins/images/33033/large/weETH.png?1701438396',
  'market_cap_rank': 19,
  'max_supply': None},
 {'coin_id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image_url': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'market_cap_rank': 20,
  'max_supply': 21000000.0},
 {'coin_id': 'ethena-usde',
  'symbol': 'usde',
  'name': 'Ethena USDe',
  'image_url': 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059',
  'market_cap_rank': 21,
  'max_supply': None},
 {'coin_id': 'hedera-hashgraph',
  'symbol': 'hbar',
  'name': 'Hedera',
  'image_url': 'https://coin-images.coingecko.com/coins/images/3688/large/hbar.png?1696504364',
  'market_cap_rank': 22,
  'max_supply': 50000000000.0},
 {'coin_id': 'weth',
  'symbol': 'weth',
  'name': 'WETH',
  'image_url': 'https://coin-images.coingecko.com/coins/images/2518/large/weth.png?1696503332',
  'market_cap_rank': 23,
  'max_supply': None},
 {'coin_id': 'avalanche-2',
  'symbol': 'avax',
  'name': 'Avalanche',
  'image_url': 'https://coin-images.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png?1696512369',
  'market_cap_rank': 24,
  'max_supply': 720000000.0},
 {'coin_id': 'litecoin',
  'symbol': 'ltc',
  'name': 'Litecoin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/2/large/litecoin.png?1696501400',
  'market_cap_rank': 25,
  'max_supply': 84000000.0},
 {'coin_id': 'the-open-network',
  'symbol': 'ton',
  'name': 'Toncoin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/17980/large/photo_2024-09-10_17.09.00.jpeg?1725963446',
  'market_cap_rank': 26,
  'max_supply': None},
 {'coin_id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image_url': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'market_cap_rank': 27,
  'max_supply': None},
 {'coin_id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image_url': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'market_cap_rank': 28,
  'max_supply': None},
 {'coin_id': 'shiba-inu',
  'symbol': 'shib',
  'name': 'Shiba Inu',
  'image_url': 'https://coin-images.coingecko.com/coins/images/11939/large/shiba.png?1696511800',
  'market_cap_rank': 29,
  'max_supply': None},
 {'coin_id': 'binance-bridged-usdt-bnb-smart-chain',
  'symbol': 'bsc-usd',
  'name': 'Binance Bridged USDT (BNB Smart Chain)',
  'image_url': 'https://coin-images.coingecko.com/coins/images/35021/large/USDT.png?1707233575',
  'market_cap_rank': 30,
  'max_supply': None},
 {'coin_id': 'coinbase-wrapped-btc',
  'symbol': 'cbbtc',
  'name': 'Coinbase Wrapped BTC',
  'image_url': 'https://coin-images.coingecko.com/coins/images/40143/large/cbbtc.webp?1726136727',
  'market_cap_rank': 31,
  'max_supply': None},
 {'coin_id': 'uniswap',
  'symbol': 'uni',
  'name': 'Uniswap',
  'image_url': 'https://coin-images.coingecko.com/coins/images/12504/large/uniswap-logo.png?1720676669',
  'market_cap_rank': 32,
  'max_supply': 1000000000.0},
 {'coin_id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image_url': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'market_cap_rank': 33,
  'max_supply': 400000000.0},
 {'coin_id': 'polkadot',
  'symbol': 'dot',
  'name': 'Polkadot',
  'image_url': 'https://coin-images.coingecko.com/coins/images/12171/large/polkadot.png?1696512008',
  'market_cap_rank': 34,
  'max_supply': None},
 {'coin_id': 'okb',
  'symbol': 'okb',
  'name': 'OKB',
  'image_url': 'https://coin-images.coingecko.com/coins/images/4463/large/WeChat_Image_20220118095654.png?1696505053',
  'market_cap_rank': 35,
  'max_supply': 300000000.0},
 {'coin_id': 'ethena-staked-usde',
  'symbol': 'susde',
  'name': 'Ethena Staked USDe',
  'image_url': 'https://coin-images.coingecko.com/coins/images/33669/large/sUSDe-Symbol-Color.png?1716307680',
  'market_cap_rank': 36,
  'max_supply': None},
 {'coin_id': 'bitget-token',
  'symbol': 'bgb',
  'name': 'Bitget Token',
  'image_url': 'https://coin-images.coingecko.com/coins/images/11610/large/Bitget_logo.png?1736925727',
  'market_cap_rank': 37,
  'max_supply': 2000000000.0},
 {'coin_id': 'crypto-com-chain',
  'symbol': 'cro',
  'name': 'Cronos',
  'image_url': 'https://coin-images.coingecko.com/coins/images/7310/large/cro_token_logo.png?1696507599',
  'market_cap_rank': 38,
  'max_supply': 100000000000.0},
 {'coin_id': 'ethena',
  'symbol': 'ena',
  'name': 'Ethena',
  'image_url': 'https://coin-images.coingecko.com/coins/images/36530/large/ethena.png?1711701436',
  'market_cap_rank': 39,
  'max_supply': None},
 {'coin_id': 'aave',
  'symbol': 'aave',
  'name': 'Aave',
  'image_url': 'https://coin-images.coingecko.com/coins/images/12645/large/aave-token-round.png?1720472354',
  'market_cap_rank': 40,
  'max_supply': 16000000.0},
 {'coin_id': 'pepe',
  'symbol': 'pepe',
  'name': 'Pepe',
  'image_url': 'https://coin-images.coingecko.com/coins/images/29850/large/pepe-token.jpeg?1696528776',
  'market_cap_rank': 41,
  'max_supply': 420690000000000.0},
 {'coin_id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image_url': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'market_cap_rank': 42,
  'max_supply': None},
 {'coin_id': 'dai',
  'symbol': 'dai',
  'name': 'Dai',
  'image_url': 'https://coin-images.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996',
  'market_cap_rank': 43,
  'max_supply': None},
 {'coin_id': 'mantle',
  'symbol': 'mnt',
  'name': 'Mantle',
  'image_url': 'https://coin-images.coingecko.com/coins/images/30980/large/Mantle-Logo-mark.png?1739213200',
  'market_cap_rank': 44,
  'max_supply': 6219316794.99},
 {'coin_id': 'bittensor',
  'symbol': 'tao',
  'name': 'Bittensor',
  'image_url': 'https://coin-images.coingecko.com/coins/images/28452/large/ARUsPeNQ_400x400.jpeg?1696527447',
  'market_cap_rank': 45,
  'max_supply': 21000000.0},
 {'coin_id': 'near',
  'symbol': 'near',
  'name': 'NEAR Protocol',
  'image_url': 'https://coin-images.coingecko.com/coins/images/10365/large/near.jpg?1696510367',
  'market_cap_rank': 46,
  'max_supply': None},
 {'coin_id': 'ethereum-classic',
  'symbol': 'etc',
  'name': 'Ethereum Classic',
  'image_url': 'https://coin-images.coingecko.com/coins/images/453/large/ethereum-classic-logo.png?1696501717',
  'market_cap_rank': 47,
  'max_supply': 210700000.0},
 {'coin_id': 'aptos',
  'symbol': 'apt',
  'name': 'Aptos',
  'image_url': 'https://coin-images.coingecko.com/coins/images/26455/large/aptos_round.png?1696525528',
  'market_cap_rank': 48,
  'max_supply': None},
 {'coin_id': 'ondo-finance',
  'symbol': 'ondo',
  'name': 'Ondo',
  'image_url': 'https://coin-images.coingecko.com/coins/images/26580/large/ONDO.png?1696525656',
  'market_cap_rank': 49,
  'max_supply': 10000000000.0},
 {'coin_id': 'internet-computer',
  'symbol': 'icp',
  'name': 'Internet Computer',
  'image_url': 'https://coin-images.coingecko.com/coins/images/14495/large/Internet_Computer_logo.png?1696514180',
  'market_cap_rank': 50,
  'max_supply': None}]

In [21]:
#Use pandas
#convert our raw data to a dataframe

Step 4: Convert to DataFrame

Now that we have a list of dictionaries (like a table), we use pandas to convert it into a real DataFrame:

In [23]:
import pandas as pd

In [25]:
df_metadata = pd.DataFrame(meta_data_list)

In [26]:
df_metadata.head()

,coin_id,symbol,name,image_url,market_cap_rank,max_supply
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,1,2.100000e+07
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2,NaN
2,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,3,1.000000e+11
3,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,4,NaN
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,5,2.000000e+08

In [27]:
df_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   coin_id          50 non-null     object
 1   symbol           50 non-null     object
 2   name             50 non-null     object
 3   image_url        50 non-null     object
 4   market_cap_rank  50 non-null     int64
 5   max_supply       24 non-null     float64
dtypes: float64(1), int64(1), object(4)
memory usage: 2.5+ KB

In [28]:
df_metadata = df_metadata.drop_duplicates(subset=['coin_id'])

In [29]:
df_metadata

,coin_id,symbol,name,image_url,market_cap_rank,max_supply
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,1,2.100000e+07
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2,NaN
2,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,3,1.000000e+11
3,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,4,NaN
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,5,2.000000e+08
5,solana,sol,Solana,https://coin-images.coingecko.com/coins/images...,6,NaN
6,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,7,NaN
7,staked-ether,steth,Lido Staked Ether,https://coin-images.coingecko.com/coins/images...,8,NaN
8,tron,trx,TRON,https://coin-images.coingecko.com/coins/images...,9,NaN
9,dogecoin,doge,Dogecoin,https://coin-images.coingecko.com/coins/images...,10,NaN
10,cardano,ada,Cardano,https://coin-images.coingecko.com/coins/images...,11,4.500000e+10
11,wrapped-steth,wsteth,Wrapped stETH,https://coin-images.coingecko.com/coins/images...,12,NaN
12,chainlink,link,Chainlink,https://coin-images.coingecko.com/coins/images...,13,1.000000e+09
13,hyperliquid,hype,Hyperliquid,https://coin-images.coingecko.com/coins/images...,14,1.000000e+09
14,wrapped-bitcoin,wbtc,Wrapped Bitcoin,https://coin-images.coingecko.com/coins/images...,15,1.270376e+05
15,wrapped-beacon-eth,wbeth,Wrapped Beacon ETH,https://coin-images.coingecko.com/coins/images...,16,NaN
16,sui,sui,Sui,https://coin-images.coingecko.com/coins/images...,17,1.000000e+10
17,stellar,xlm,Stellar,https://coin-images.coingecko.com/coins/images...,18,5.000179e+10
18,wrapped-eeth,weeth,Wrapped eETH,https://coin-images.coingecko.com/coins/images...,19,NaN
19,bitcoin-cash,bch,Bitcoin Cash,https://coin-images.coingecko.com/coins/images...,20,2.100000e+07
20,ethena-usde,usde,Ethena USDe,https://coin-images.coingecko.com/coins/images...,21,NaN
21,hedera-hashgraph,hbar,Hedera,https://coin-images.coingecko.com/coins/images...,22,5.000000e+10
22,weth,weth,WETH,https://coin-images.coingecko.com/coins/images...,23,NaN
23,avalanche-2,avax,Avalanche,https://coin-images.coingecko.com/coins/images...,24,7.200000e+08
24,litecoin,ltc,Litecoin,https://coin-images.coingecko.com/coins/images...,25,8.400000e+07
25,the-open-network,ton,Toncoin,https://coin-images.coingecko.com/coins/images...,26,NaN
26,leo-token,leo,LEO Token,https://coin-images.coingecko.com/coins/images...,27,NaN
27,usds,usds,USDS,https://coin-images.coingecko.com/coins/images...,28,NaN
28,shiba-inu,shib,Shiba Inu,https://coin-images.coingecko.com/coins/images...,29,NaN
29,binance-bridged-usdt-bnb-smart-chain,bsc-usd,Binance Bridged USDT (BNB Smart Chain),https://coin-images.coingecko.com/coins/images...,30,NaN
30,coinbase-wrapped-btc,cbbtc,Coinbase Wrapped BTC,https://coin-images.coingecko.com/coins/images...,31,NaN
31,uniswap,uni,Uniswap,https://coin-images.coingecko.com/coins/images...,32,1.000000e+09
32,whitebit,wbt,WhiteBIT Coin,https://coin-images.coingecko.com/coins/images...,33,4.000000e+08
33,polkadot,dot,Polkadot,https://coin-images.coingecko.com/coins/images...,34,NaN
34,okb,okb,OKB,https://coin-images.coingecko.com/coins/images...,35,3.000000e+08
35,ethena-staked-usde,susde,Ethena Staked USDe,https://coin-images.coingecko.com/coins/images...,36,NaN
36,bitget-token,bgb,Bitget Token,https://coin-images.coingecko.com/coins/images...,37,2.000000e+09
37,crypto-com-chain,cro,Cronos,https://coin-images.coingecko.com/coins/images...,38,1.000000e+11
38,ethena,ena,Ethena,https://coin-images.coingecko.com/coins/images...,39,NaN
39,aave,aave,Aave,https://coin-images.coingecko.com/coins/images...,40,1.600000e+07
40,pepe,pepe,Pepe,https://coin-images.coingecko.com/coins/images...,41,4.206900e+14
41,monero,xmr,Monero,https://coin-images.coingecko.com/coins/images...,42,NaN
42,dai,dai,Dai,https://coin-images.coingecko.com/coins/images...,43,NaN
43,mantle,mnt,Mantle,https://coin-images.coingecko.com/coins/images...,44,6.219317e+09
44,bittensor,tao,Bittensor,https://coin-images.coingecko.com/coins/images...,45,2.100000e+07
45,near,near,NEAR Protocol,https://coin-images.coingecko.com/coins/images...,46,NaN
46,ethereum-classic,etc,Ethereum Classic,https://coin-images.coingecko.com/coins/images...,47,2.107000e+08
47,aptos,apt,Aptos,https://coin-images.coingecko.com/coins/images...,48,NaN
48,ondo-finance,ondo,Ondo,https://coin-images.coingecko.com/coins/images...,49,1.000000e+10
49,internet-computer,icp,Internet Computer,https://coin-images.coingecko.com/coins/images...,50,NaN

In [31]:
df_marketdata = pd.DataFrame(market_data_list)

In [32]:
df_marketdata.head()

,coin_id,current_price,market_cap,total_volume,high_24h,low_24h,price_change_24h,price_change_pct_24h,market_cap_change_24h,market_cap_change_pct_24h
0,bitcoin,117829.00,2346720953499,73586281209,124128.000,117640.00,-3944.717343,-3.23939,-7.784807e+10,-3.21080
1,ethereum,4532.39,548351156148,64614666756,4779.000,4527.03,-205.324744,-4.33384,-2.320123e+10,-4.05934
2,ripple,3.07,182238082615,11026388437,3.340,3.06,-0.206499,-6.30389,-1.206786e+10,-6.21075
3,tether,1.00,165086538617,164780693245,1.001,1.00,0.000336,0.03361,5.886591e+07,0.03567
4,binancecoin,833.78,116074726816,2690525449,866.960,829.68,-10.136670,-1.20114,-1.464499e+09,-1.24597

In [33]:
df_marketdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   coin_id                    50 non-null     object
 1   current_price              50 non-null     float64
 2   market_cap                 50 non-null     int64
 3   total_volume               50 non-null     int64
 4   high_24h                   50 non-null     float64
 5   low_24h                    50 non-null     float64
 6   price_change_24h           50 non-null     float64
 7   price_change_pct_24h       50 non-null     float64
 8   market_cap_change_24h      50 non-null     float64
 9   market_cap_change_pct_24h  50 non-null     float64
dtypes: float64(7), int64(2), object(1)
memory usage: 4.0+ KB

In [35]:
df_marketdata = df_marketdata.drop_duplicates(subset=['coin_id'])

In [36]:
df_marketdata

,coin_id,current_price,market_cap,total_volume,high_24h,low_24h,price_change_24h,price_change_pct_24h,market_cap_change_24h,market_cap_change_pct_24h
0,bitcoin,117829.000000,2346720953499,73586281209,124128.000000,117640.000000,-3944.717343,-3.23939,-7.784807e+10,-3.21080
1,ethereum,4532.390000,548351156148,64614666756,4779.000000,4527.030000,-205.324744,-4.33384,-2.320123e+10,-4.05934
2,ripple,3.070000,182238082615,11026388437,3.340000,3.060000,-0.206499,-6.30389,-1.206786e+10,-6.21075
3,tether,1.000000,165086538617,164780693245,1.001000,1.000000,0.000336,0.03361,5.886591e+07,0.03567
4,binancecoin,833.780000,116074726816,2690525449,866.960000,829.680000,-10.136670,-1.20114,-1.464499e+09,-1.24597
5,solana,193.090000,104355912979,14575684799,209.180000,191.720000,-7.052200,-3.52359,-3.144537e+09,-2.92514
6,usd-coin,0.999802,67077872258,25927141396,0.999855,0.999711,-0.000007,-0.00065,6.674255e+08,1.00500
7,staked-ether,4525.490000,40011158534,153147961,4769.920000,4493.230000,-204.235816,-4.31814,-1.755158e+09,-4.20233
8,tron,0.358334,33925744010,2293355417,0.369488,0.358099,-0.002808,-0.77746,-3.072367e+08,-0.89749
9,dogecoin,0.222995,33611452009,4865177488,0.253948,0.222593,-0.020618,-8.46344,-2.970233e+09,-8.11945
10,cardano,0.902098,32869827847,5805966334,1.014000,0.871277,0.027837,3.18403,1.115693e+09,3.51354
11,wrapped-steth,5495.480000,17576054093,127646191,5776.070000,5464.450000,-221.137084,-3.86832,-7.896719e+08,-4.29970
12,chainlink,22.310000,15133428388,2012096752,24.250000,22.300000,-1.431168,-6.02879,-9.469022e+08,-5.88857
13,hyperliquid,45.250000,15003246342,539428642,48.820000,44.400000,-1.992064,-4.21658,-7.553546e+08,-4.79328
14,wrapped-bitcoin,117847.000000,14968581237,509332498,123882.000000,117569.000000,-3811.847882,-3.13323,-4.952748e+08,-3.20279
15,wrapped-beacon-eth,4872.000000,14441232690,43802278,5142.460000,4858.000000,-216.782715,-4.26001,-5.749422e+08,-3.82882
16,sui,3.760000,13247081512,2668270207,4.160000,3.750000,-0.237476,-5.93654,-7.750127e+08,-5.52708
17,stellar,0.422022,13224869430,871259898,0.465095,0.418613,-0.029952,-6.62696,-9.196045e+08,-6.50151
18,wrapped-eeth,4866.170000,12647043574,48900247,5124.170000,4850.890000,-209.392609,-4.12550,-5.632365e+08,-4.26362
19,bitcoin-cash,589.220000,11731414298,443378144,626.020000,586.680000,-23.717185,-3.86945,-4.837616e+08,-3.96033
20,ethena-usde,1.001000,10968720718,740059437,1.002000,0.998585,-0.000336,-0.03361,9.385200e+07,0.86302
21,hedera-hashgraph,0.248491,10536967167,626406778,0.275162,0.247702,-0.015319,-5.80675,-6.465422e+08,-5.78121
22,weth,4543.000000,10259359160,142815731,4780.970000,4505.130000,-193.343607,-4.08212,-8.236914e+08,-7.43199
23,avalanche-2,23.660000,9990533374,1113272061,25.940000,23.540000,-1.537862,-6.10400,-6.368542e+08,-5.99258
24,litecoin,120.900000,9214851026,1241076589,133.600000,120.750000,-9.232922,-7.09522,-6.743924e+08,-6.81945
25,the-open-network,3.410000,8736562593,453518019,3.630000,3.380000,-0.093705,-2.67741,-2.419374e+08,-2.69463
26,leo-token,9.280000,8562995341,4581109,9.290000,9.230000,0.030639,0.33137,2.829324e+07,0.33151
27,usds,0.999557,7618217482,27132849,1.000000,0.999224,-0.000075,-0.00749,-1.233202e+08,-1.59297
28,shiba-inu,0.000013,7571320526,433689723,0.000014,0.000013,-0.000001,-7.39603,-6.023272e+08,-7.36914
29,binance-bridged-usdt-bnb-smart-chain,0.998436,6783599138,2238065774,1.009000,0.988595,-0.002095,-0.20941,-3.139729e+06,-0.04626
30,coinbase-wrapped-btc,117923.000000,6573077649,796719123,123939.000000,117450.000000,-3700.283456,-3.04241,-1.786846e+08,-2.64649
31,uniswap,10.900000,6547795283,971758174,12.220000,10.850000,-1.138573,-9.45704,-6.912911e+08,-9.54942
32,whitebit,45.280000,6520092970,90182076,47.210000,45.180000,-1.316554,-2.82571,-1.894566e+08,-2.82369
33,polkadot,3.990000,6070206309,540270259,4.360000,3.960000,-0.244512,-5.77925,-3.728199e+08,-5.78641
34,okb,93.810000,5684692960,1157029004,113.530000,92.740000,-9.551101,-9.24063,-5.325175e+08,-8.56522
35,ethena-staked-usde,1.190000,5498399352,109107555,1.190000,1.190000,-0.000561,-0.04730,1.933524e+07,0.35289
36,bitget-token,4.550000,5185317652,308836325,4.890000,4.540000,-0.246797,-5.14654,-2.746161e+08,-5.02966
37,crypto-com-chain,0.151527,4909400412,48779095,0.168316,0.150516,-0.014015,-8.46634,-4.415636e+08,-8.25204
38,ethena,0.727168,4820555660,1529839957,0.781403,0.704473,-0.054235,-6.94076,-3.849417e+08,-7.39491
39,aave,310.100000,4717875401,808795132,339.630000,309.250000,-17.231374,-5.26423,-2.665261e+08,-5.34720
40,pepe,0.000011,4672092407,1473870423,0.000013,0.000011,-0.000001,-9.38591,-4.722632e+08,-9.18022
41,monero,247.450000,4568916934,58921500,258.920000,246.300000,-8.920204,-3.47939,-2.010898e+08,-4.21571
42,dai,0.999813,4025076777,195793484,1.000000,0.999334,-0.000125,-0.01248,9.563177e+07,2.43372
43,mantle,1.100000,3697099635,396378074,1.200000,1.085000,-0.022169,-1.97274,-9.598442e+07,-2.53051
44,bittensor,367.180000,3529108981,215071345,400.910000,365.930000,-24.737801,-6.31201,-2.403973e+08,-6.37742
45,near,2.780000,3470880133,520685419,3.050000,2.770000,-0.158979,-5.40600,-1.899899e+08,-5.18975
46,ethereum-classic,22.240000,3412128761,284302867,24.410000,22.150000,-1.907490,-7.89947,-2.799338e+08,-7.58204
47,aptos,4.740000,3244430760,601934349,5.140000,4.710000,-0.233290,-4.69376,-1.557770e+08,-4.58140
48,ondo-finance,0.995541,3149417178,377495933,1.110000,0.991047,-0.072146,-6.75721,-2.221249e+08,-6.58823
49,internet-computer,5.540000,2981686038,106939821,6.080000,5.520000,-0.393143,-6.62076,-2.059662e+08,-6.46138